import * as React from "react"
import type { HeadFC, PageProps } from "gatsby"
import "../index.scss"

const CSVSPage: React.FC<PageProps> = () => {
  return (
    <div className="container">
    <h1>Art and Duty</h1>
		<div><a href="/">← Home</a></div>
        <h3>1</h3>
		<p>
        I was with a friend of mine, let’s call him Stewart, who is a young aspiring musician, the frontman of a rock band presently working on their demos. “I don’t see myself ever being happy,” he told me. “The idea of being happy is for other people, regular people. To me, that’s just not what life is about at all, whatsoever.”
        </p>
		<p>
        Stewart’s attitude is tragic but fair. It seems difficult to imagine how happiness could coincide with a life lived through intense devotion to one’s art. Being an artist is not easy or comfortable. First, you have to get the money to live in the world, just to be able to survive. This is stressful, because for “normal people” (non-artists), this is the primary thing they care about. If they are getting money and getting laid, life is good. They have no reason not to pour their libido solely into income-generating activities. When they are off work, they twiddle their thumbs, turn on the TV for distractions, don’t know what to do with themselves. However, for the artist, his mind is always elsewhere, churning through un-actualized ideas and the agony about their lack of actualization.  Yet he must participate in the rat race as well, as someone with half his heart there.
        </p>
		<p>
        Once that obligation to make income is met, the artist must set to his work. At this point, the non-artist thinks — “well, good for him, he is doing what makes him happy”. As artists know, nothing could be further from the truth. The artistic process is as a rule one of agony, though it is punctured by unpredictable ecstasies as well. The artist must repeatedly set his inner blade to himself in the cruelest of ways, paring down his vision to its core, discarding draft after draft, tortured by his own inadequacy compared to his ideal, until his work is “done” — which is never accomplished in the moment, it does not await the artist in the here and now, it is ages away, it is something that happens only in retrospect when the zenith of his creative lifetime is reached.
        </p>
		<p>
        Nor is it the case that finishing the work and having it out in the world brings happiness. Once the artist’s work is external to himself and consumed by the public, it only brings immense dysphoria for the artist to see the gap between his own conception of his work and the manner in which the public consumes it — the audience inevitably “misses the point”. One can think of the despair felt by Wagner after working on his epic opera <i>The Ring</i> for twenty-six years and debuting it at Bayreuth (a destination town set up for the occasion) experiencing the heights of his stardom up to that point but only feeling the cheapness of the bourgeois audience and their flattery as they consumed his work, engaged more in the empty frivolity of the occasion than ecstatic immersion in the art in the way Wagner envisioned. (Perhaps these philistinic European bourgeois were the prototype for today’s Coachella girls Instagramming themselves in distasteful Native American headdresses at the Kendrick Lamar set.)
        </p>
		<p>
		Thus, there is no point during the artistic process where the artist can project a future happiness. Having laid out this sad state of affairs, why make art?
		</p>
		<p>
        “I just know this is what I was meant to do,” Stewart told me. “It’s what I was made for, it’s the only thing I’ll be good at. I have to follow my duty.”
        </p>
        <p>
        The duty of the artist. This is the question of the present essay. Perhaps the artist is not different from any other serious adult in our society — he must suspend desire for happiness to engage in what he believes to be his <i>duty</i>. 
        </p>
        <p>
        The question of our personal duty is something we must all discover. If any man does not make the sacrifice of his immediate pleasures for a <i>duty</i> he finds in the world, he will not accomplish anything — no one will apply himself to a career, start a business, go into politics, crusade for social justice, fight in war, build a church or other community organization, raise children, etc. If he chooses immediate pleasures over duty, he will be a cheap pleasure-seeker who masturbates, watches junk television, and crushes Coors Light by the pack. Doing this day after day, he will fail to even attain his goal of happiness, as he will know only the pangs of regret in his lack of actualization. He will fall into disrepute amongst his peers, and he will experience himself as a kind of animate nothingness, who has not even lived.
        </p>
        <p>
        This is the complicated condition of man. But there is a deeper paradox here for the artist, one which ensures his continued torments. For someone like, for instance, the soldier, it is <i>conceptually</i> straightforward for him to suspend pleasures in the embrace of his duty — and thus he receives a secondary pleasure in renunciation. He renounces leisure, the company of women, and his own freedom. He embraces painful physical discipline in order to submit himself to the absolute duty to annihilate the enemy and bring about his army’s victory.
        </p>
        <p>
        I told my friend Stewart — it’s not that I disagree with your point about duty, but there is an irony in you saying this, because from an external perspective, you appear to be the most self-interested hedonist. You go on cocaine benders weekly, you’re constantly trying to have sex with models, and you’re trying to be this rockstar, this transcendentally cool person who everyone admires and wants to be like. How do you differentiate — within yourself — your <i>duty</i>, versus your impulses to just follow sheer egoic gratification? He didn’t have an answer to this, and neither did I.
        </p>
        <p>
        From the perspective of a non-artist, this type of lifestyle of excess Stewart is living, combined with his insistence on duty, might seem like sheer hypocrisy. But it is not, and I am not calling my friend a hypocrite. Why? Because the artist’s duty is also the duty to be a sensualist. The artist must provide his audience with a sublimely beautiful sensual experience. How can he do this if he has not lived sensually himself? How could these Romantic poets write about doomed love and yearning if they were not always trying to carry on passionate affairs with aristocratic women? How can one sing about the sublimely tragic futilities of pleasure seeking if he has not gone to the ends of excess in opium and absinthe, even knowing that nothing waits for him at the end, other than yet another moment of almost grasping the inaccessible only to have it slip away, a doomed excess only redeemed through providing fuel for his poetry?
        </p>
        <p>
        The greatest case of this yet might be in the experience of the contemporary rapper, who is essentially compelled by his audience to lavishly spend money on cars, women, clothing, exotic destinations, etc., only to make music about how he did all this and still feels an immense spiritual void inside him. “<i>Lord, let me hit this ho, so I have something to rap about</i>” — Freddie Gibbs.
        </p>
        <p>
        Therefore, the duty of an artist, unlike the duties of the other vocations, cannot be attained by renouncing pleasure. Rather the artist has, in a certain respect, the <i>opposing</i> duty — he has the duty to go all the way to the ends of his sensual pleasure, the duty not to renounce, the duty to go <i>through</i> the pleasures which the other members of society in their duties must renounce, in a quest which eventually achieves what is not possible to attain through these pleasures, and can only be projected into the sublime of the aesthetic experience the resulting artwork will establish. 
        </p>
        <p>
        As such, the artist has the most severe and extreme duty of all, as he is the only one whose duty does not even allow himself to escape the false, itinerant, worldly pleasures through the “true” pleasure of renunciation — which, as is well known, is the only pleasure which can be guaranteed.
        </p>
		<h3>2</h3>
		<p>
        Why are some people artists and others are not? Stewart observed that all our artist friends are, put bluntly, “fucked up” — they have often severe mood dysregulations which demand a need to constantly wrestle with one’s own subjectivities in a way that other people don’t seem to experience or understand.	</p>
        <p>
        Which comes first, the chicken or the egg? Are artists understandably fucked up, given the aforementioned pains involved in the lifestyle, or do fucked up people gravitate to the arts for some reason? Stewart reasonably said that the question is undecidable, it its always necessarily both.
        </p>
        <p>
        The founding document of Romanticism, which is the same as artistic modernism, should be considered to be <a href="https://www.gutenberg.org/files/45315/45315-h/45315-h.htm">William Blake’s <i>Marriage of Heaven and Hell</i></a>. Blake posits that there are two types of men — “angels”, and “devils”. Angels are those who abide by social order, assimilate easily into society, and enforce norms. Devils are the artists and poets like Blake himself, who are threatening to social order in their nonconformity. Blake is emphatically <i>not</i> making the gesture which Lord Byron and others after him would, which is to praise Lucifer or the devil himself as the hero to man, against the entire history of organized religion which represses the freedom promised by the devil. Blake presents himself as a faithful and obedient Christian, and merely uses the terms “angel” and “devil” in an inverted way for ironic effect — while from the eyes of <i>society</i>, he is a devil, it is clear Blake sees himself as entirely virtuous and imagines that Jesus Christ himself would agree. 
        </p>
		<p>
        Blake writes of how "now the sneaking serpent walks in mild humility, and the just man rages in the wilds where lions roam”. The implication is that while Blake considers himself a proper Christian, there is no room for him in his era’s watered-down Christianity, which preaches a dull, drumming doctrine of moral conformity. What Blake instead seeks are the kind of fervent moments of access to the sublime which religion promises, and which prophets in the Bible are described as experiencing. These moments of ecstasy and inspiration are what Blake, the <i>poet</i>, is engaging in a lifelong quest for. His prescription for the world — to fix the deficit of inspired prophecy in the church — is that <i>artists must become prophets</i>.
        </p>
		<p>
        Prior to artistic modernism, there was not this conception today we have of Art as a united sphere of discovery which is inherently valuable in itself. Rather, there were “the arts”, various things like music, theater, table-making, painting, which were meant to be enjoyed and make life more beautiful — that is, for the wealthy, who could afford this sort of luxury of ornament. The romantic movement of the early nineteenth century which followed Blake would be the one to bring about the conception we have today, with the generational slogan of “art for art’s sake”. This was a call which was originally seen as radical and transgressive, though is now totally accepted by all and gives us our concept of Art, which we believe to be one of the most supreme goods in life, which gives life its meaning. 
        </p>
        <p>
        What Art has become today is but one enterprise to replace the function of religion after the death of God. While in law and state affairs the lawful mandate of God can be replaced by Man’s Reason, modern Art is necessary to supplant the other, “hidden”, face of God — the experience of the sublime we discover in contemplating His presence (which we no longer have immediate access to, because rationality has divested us of it). It is in Blake where we see most explicitly the transition of this function away the church and over into the establishment of an autonomous sphere of Art, inaugurating Art as “the religion of modernity”.
        </p>
		<p>
        Blake’s <i>Marriage of Heaven and Hell</i> should also be considered the original document of “left-wing Nietzscheanism”, <i>avant la lettre</i>. Both Blake and Nietzsche argue that the strong (devils) are effectively oppressed by the weak (angels), rather than the other way around. They seek a restoration away from this backwards position, and thus for the strong to stand up, shake off their dusty yokes, and restore their superiority. However, Nietzsche infamously incorporates aspects of the proto-Hitlerian reactionary German milieu he existed within into his framing of this struggle — Nietzsche, as is well known, gestures at how the noble Aryan warrior spirit is supposedly oppressed by the petty small-minded spirit of the Jewish-influenced bourgeois.
        </p>
		<p>
        For Blake, who is a Christian advocate of “mercy” and “peace”, there is no dreaming of restoring a kind of violent warrior ethic or fighting a racial conflict in this way. Rather, the “strong” are meant to be understood as those with strong souls — they are consumed by intense passionate desires. In actual extant society, they are seen as pitifully inept, even feeble and mentally ill — Blake himself likely would be diagnosed a schizophrenic if he lived today — but their surface-level inadequacy is only a reflection of the fact that their souls are not “weak” enough to accept external imposition into socially regulated productivity, which wants to trample their souls’ desires to individuate on their own terms. We can think of some of today’s “devils” as a subset of the neurodivergent — those with autism or ADHD, for instance — who struggle with basic socially-imposed tasks because their minds and hearts are consumed with projects of individual passion and obsession, which they often accomplish with prodigious skill.
        </p>
        <p>
        The political project of Nietzsche is poorly understood, but it is basically to combine the spirit of the artistic avant-garde with militarism — his aspiration is that an actual violent conquest would be carried out to solve the “crisis of European nihilism” by uniting Europe under a new state in which sovereignty and social life is expressed through a total-work-of-art similar to the Wagnerian festival — thus making the replacement of Romantic art in modernity over the medieval role of the Catholic church fully complete, in politics as well as aesthetic and spiritual experience. The gradual realization of the impossibility of this dream and its inevitable usurpation by the Hitlerian project for the total European state seems to have been what made Nietzsche go insane.
        </p>
        <p>
        Many have questioned how it is possible for various writers (Bataille, Foucault, Deleuze, etc) to present a “left-wing” interpretation of Nietzsche. Did Nietzsche not write that there were natural superiors and inferiors, that aristocracy needed to be restored, that these aristocrats need to embrace <i>cruelty</i> over the weak, and that they need to restore <i>slavery</i>? Does this not make him the reactionary writer <i>par excellence</i>?
        </p>
        <p>
        The way to understand this adoration of Nietzsche from left-leaning bohemians is to understand that Nietzsche’s aim is to put Art on the throne of the world. For Nietzsche, the necessity of an aristocratic class, which believes it has a mandate to own slaves, does not not come from this class’s desire to brutally exploit and dominate their inferiors, nor even their desire to control their inferiors (their attitude towards their inferiors is one of haughty  indifference). Rather, it is simply that in order to overcome nihilism, there must be a class tasked solely towards spiritual pursuits, so that they may discover a source of value for the world. It is only necessary that they are freed of the burden to work, so that they may have leisure, and space to explore sensuality. In order for them to be freed from the burden to work, they must live off the backs of the labor of others.
        </p>
        <p>
        Today’s “Nietzschean” class is the creative class of the culture industry, which perhaps has its fated marriage with militarism in its alliance with the CIA and the American imperialist apparatus. Looking at today’s creative class, we can see how the relationship of these wolfish “devils” producing media for the sheeplike “angels” who consume their fantasies — is one of cruelty. 
        </p>
        <p>
        The “angelic” normies think that artists are mostly narcissistic homosexuals who would be better off getting a real job, but meanwhile the normies’ lives are structured around consuming the fantasies of these artists in entertainment products and music. This is what gives the normies’ banal lives their glimpses of intensity. On the other hand, the true artist despises his commercial audience, perceiving them as imbecilic and needing to be shepherded in order for any of the artist’s meaning to come across at al. But he appreciates the audience’s value in providing funds for the artist to live a life in an aristocratic or bohemian sphere separate from vulgar labor. 
        </p>
        <p>
        The more “avant-garde” qualities the Art has, the more heightened this antipathy is, and the closer the artist is to fulfilling his “Nietzschean” mandate of pursuing spiritual extremes without regard for worldly trivialities.
        </p>
        <p>
        Kant, writing contemporaneously with Blake, provides one of the canonical theories of artistic beauty as seen from the perspective of Enlightenment Reason. Famously, in <i>Critique of Practical Reason</i>, the second volume of Kant’s trilogy, Kant provides the reader with his ethics, in which he tells us we are obligated to discover a rational Moral Law which must be rigorously adhered to once it is discovered. But in the third volume, the <i>Critique of Judgment</i>, Kant problematizes his own rationality by introducing the category of the Sublime.
        </p>
        <p>
        The Sublime is a type of aesthetic experience which cannot be discovered in objects of nature such as flowers; nature can merely be “beautiful”. The Sublime is an intellectual experience discovered in objects which confront our rational faculty with a kind of traumatic experience: the impossibility of confronting and assimilating them. This sublime experience contains both displeasure and pleasure. The displeasure comes from the initial shock at the failure to assimilate them into our rational schematism. The pleasure comes from the staggering sense of “infinity” experienced by the repeated failure to assimilate the object.
        </p>
        <p>
        The Sublime for instance can be experienced in a painting such as Hieronymous Bosch’s <i>Garden of Earthly Delights</i> (a kind of depiction of a “marriage of heaven and hell” in its own right). The viewer attempts to grasp the strange agglomerations of bodies and activities in this fantastic world in which the Antichrist is given free reign to deceive men, yet ultimately is incapable of assimilating the strangeness of the artwork into himself. 
        </p>
        <p>
        The Sublime experience is described by Kant as “mathematical” because its strange relationship with Reason is analogous to those paradoxes presented by mathematical set theory, which as Gödel would later demonstrate, ultimately leads to the impossibility of having any complete well-grounded system of knowledge. Any well-founded set must be able to posit “exceptional” conditions external to itself, so as such is not complete. To have a set which contains all things, a definition of a new set must be created which includes the exception, but then this set will present its own exception. Confronting this impossibility of representing the totality presents us with a dizzying tower towards of infinity — we create a new set, then another set, then another set, and yet we get nowhere — this is our humility before the sublime supremacy of God. 
        </p>
        <p>
        Ultimately, this experience of infinity forces us to confront the truth that the rational Moral Law will never be completely explicated — in fact, it is possible for it to be disrupted, broken apart, scattered to the winds like the Tower of Babel at any time, through this kind of traumatic experience of the Sublime. Thus, Kant’s aesthetic philosophy problematizes his ethics.
        </p>
        <p>
        The typical “angelic” civilian today is he who is repeatedly violated by the romantic Sublime, in a war waged on him by the creative class, who saturate his mind with strange fantasies which he cannot stop enjoying but which problematize a straightforward ethical stance in his daily life. The average American knows to obey the law but also knows that as a free American spirit he is to be “rock and roll”, because of neo-Romantic poets in the form of rockstars taunting him with Sublime fantasies of a world of aesthetic excess and freedom beyond daily conformity. Today, the rockstar figure has evolved into the rapper, who actively represents all forms of vice and antisocial excess, but is able to aesthetically inscribe it in a Sublime which is impossible for the masses to resist exalting. Thus the artist wages war on the social order, yet experiences only adoration from those enmeshed in the order he mocks, because he gives them their meaning.
        </p>
        <p>
        The “devilish” artist is he who has spiritual impulses within him that are oppressed by moral conformity. Without fighting his individualist struggle and finding a non-conformist role in the world for himself, he is doomed to being impotent, abused, and misunderstood. He initially must fight for his right to express himself by staging a hysterical performance in which he demands that the world, who he hates, nevertheless recognize him for his unique creative potential. This is always the sentiment of rockstars and rappers when they begin their careers, posing with a middle finger to the camera to show that they are a kind of gifted rascal with a heart of gold.
        </p>
        <p>
        At the height of his creative prowess, having been accepted in his role and given an audience, the artist finally gives to the world his Sublime, his “beautiful dark twisted fantasy” as expressed in full, and thus accomplishes his revenge on the public. The artist “rapes” the public by thrusting into them the trauma of his Sublime which infinitely problematizes the sterile rhythms of moral conformity the artist has flown from. He leaves the audience fully worse off, his devilish condition being transferred onto them, but with the bruised angels fully grateful for the experience.
        </p>
		<h3>3</h3>
		<p>
        Let’s return to the question — why are some people artists, but others are not?
        </p>
		<p>
        Why do some people experience this deep yearning at the core of their being to make art, while others have never experienced this at all? If we turn to psychoanalysis, the answer can only be one thing — one’s deepest ambitions are determined in advance by a psychosexual complex acquired in early childhood.
        </p>
		<p>
		Lacan tells us that we start our lives with a deep inner yearning to be recognized in our existence by the symbolic order around us. There is something in us, we feel, that is the true expression of our being. If only people could see that and see us for who we really are, we feel — then people would know us as we know ourselves, and they would love us, and understand us. And somehow hearing our own name that people repeat in the world fails to capture this totally or at all; we cringe internally hearing the way people talk about us, there is something missing in the way they represent us, it doesn’t reflect what we feel is really <i>in</i> us, if only they could see.
		</p>
        <p>
        This “essence” which we feel in ourselves is a kind of unconscious strategy we adopt to get our parents’ attention during the liminal period emerging from being totally helpless in our parents’ care, while we are learning how to speak. In this stage, we are introduced to the trauma of suddenly having the duty to articulate our desires to have them reciprocated by our parent (rather than just throwing a fit and have our parent intuit what we want).
        </p>
        <p>
        The problem when it comes to the desire for having our “true self” recognized is — not only is our unconscious strategy “empty” in a sense, being an amalgamation of infantile gestures looking for attention rather than any concrete form of personhood another adult would find meaningful or respect — but it is also embarrassing and obscene — if the time came to present it in the open, it would be a revealing display of one’s most perverted and pathetic sexual fantasies. Why? Because psychoanalysis tells us the strategy for seeking recognition from one’s parent becomes inevitably grafted on to the sex drive as it develops — for this reason, if one for instance at five years old finds that the way to become important in the parent’s world is to force the parent to look at oneself, a man might find the height of sexual pleasure to be found when his lover looks at his penis; the actual act of sex being less important than this moment of visual recognition. This man would then go about the world believing that he has some unique essence to his being; if only other people would recognize it. But he cannot articulate what it is. He is not comfortable enough to disclose what this essence is unless he is in a condition of intimacy. When he is lulled into this state of intimacy, his lover draws it out more and more — <i>what is it you really want</i>? As it turns out, what he really wants is obscene and humiliating — as his true wish is drawn out from him, and he understands what it really is he needs “recognized”, he is horrified to grasp this understanding of who he really is, even to himself. He feels shame after his sexual action, and the script flips — he now wakes up the morning after and thinks, “that wasn’t proper, that wasn’t me”. 
        </p>
        <p>
        The disgusting conclusion of psychoanalysis, which leaves it widely hated, is that the mature roles we choose in the world are extensions of these basic psychosexual fantasies we develop in the beginnings of our lives. Since we are driven to seek recognition by our peers through impulses deriving from these fundamental fantasies, the only way we can feel like our energies are fulfilled through our actions in the world are if our roles match these obscene and fantastic desires in some kind of sublimated socially useful way. The man we were describing In the previous paragraph, who has the sexual need to be looked at, might be able to take on a role in some highly visible function, such as a conductor in an orchestra, in which the conductor’s baton could serve as a symbolic substitute for his erect penis.
        </p>
        <p>
        If some people are natural “devils” and find that they have no role in the world which matches their psychic energy, it may be the case that this is because they have a less common type of inner fantasy. For instance, (at the risk of presenting an example which is perhaps artificial and contrived), imagine if at some pivotal moment of childhood development and coming to self-awareness, a child experiences his mother and father calling his name in a way that makes it impossible for him to separate who is who. This child as an adult could become a bisexual who is perennially seeking threesome scenarios in which he has both a male and female lover who are able to recognize his being simultaneously.
        </p>
        <p>
        A child who internalizes the basic Oedipal structure of “I must become like my father, in order to love a woman who reminds me of my mother” will not have a problem finding a role in the world to fulfill his fantasy as long as his father is a reputable man —  he can simply play the same role in the world his father did and become reputable too, and find a wife.  
        </p>
        <p>
        But now take our hypothetical threesome-obsessed bisexual character. Perhaps he will be tormented by constant yearnings of living where he has both a husband and a wife paying attention to him. Not having any way to convince people to make this happen (let alone in a way which is socially accepted) he may be forced to displace his fantasies into the realm of art. Maybe there can be some science-fiction story about an alien planet where there are three sexes and in which such arrangements are common. 
        </p>
        <p>
        This type of artistic piece, if it existed, would become a Sublime object for him, as this would present him with his fantasy in the clearest possible form, as well as tormenting him with the impossibility of living it. This principle, outlined somewhat in caricature here, is likely why avant-garde art spaces and a preponderance of Queer sexualities nearly always coincide. 
        </p>
        <p>
        Lacan says that in the psyche there are three different kinds of ways to wish for something. These are somewhat confusingly named and not intuitive to grasp, so I hope the reader will be somewhat patient here as I elaborate them. The first way is what Lacan calls “need”. The needs are the most basic biological urges — to eat when hungry, to drink when thirsty, to shit when full, to piss when one needs to piss. These are basic enough to exist prior to the immersion in the social sphere and its language and laws which we are all trapped in, and so are not especially interesting, and after this we do not need to mention them again.
        </p>
        <p>
        Secondly, there is what Lacan calls “drive”. Drive exists as a result of a <i>demand</i> made by the big Other — the “big Other” is essentially a name for the totality of social relations, congealed into a singular imagined persona. Society asks requests of its members, and its members must fulfill it. This is “drive” — this concept should be also seen as not particularly hard to understand at this point.
        </p>
        <p>
        Thirdly, there is what Lacan calls “desire”. In this case, the subject is responding to an ask of the big Other, not for a specific offering or task from the person, but in the case when the Other is asking <i>for the subject themselves</i>. The Other no longer wants something from the subject, but actually <i>wants the subject</i>. In other words, the Other is promising to be capable of loving and cherishing the subject for the subject’s being alone — though, like any lover, this is conditional, and comes with strings attached.
        </p>
        <p>
        Drive is circular and repetitive — though the subject fulfills the demand of the Other, the Other insists on demanding it again and again, and the subject fulfills it again and again. Desire, on the other hand, is dialectical, an expanding spiral. The subject attempts to fulfill the role the Other wants of him, and the Other tells him “that was good, but that still wasn’t quite what I was looking for…”. While drive is a mere obligation, desire is a <i>duty</i>, a position which must be stuck to, even in the face of continuous defeat.
        </p>
        <p>
        Drive is pagan and desire is Abrahamic. In drive, the Other plays the role of the pagan god, who is a kind of primordial Master who continuously demands offerings. Under desire, on the other hand, the Other, or God, does not demand material sacrifices to be placated, but loves the subject. The subject must sacrifice himself, or his own independence, to receive the love of God — love in exchange for duty — duty in itself being a reciprocal form of love. But, like the Abrahamic God of the Old Testament issuing forth his will in terrifying thunderclaps to the prophets, the Other’s love is semi-contingent on his subject following his divine plan, which is never exactly or precisely revealed or spelled out. The subject is always in a state of terror and guesswork attempting to make sure he is obeying the plan of God — always asking himself <i>what does he really want</i>?
        </p>
        <p>
        The entire program of Lacanian psychoanalytic healing is to get around the problem of “desire” and its neverending recursive guesswork. Why do we need to get away from this guessing? Because there is no actual answer to the question of what the Other truly wants which will make it love the subject. Why? Because God is dead. In modernity, God as the basis of social life has disappeared, and all we have is the Other — this structural placeholder for where God was once positioned, now stripped of its divinity and holiness. There is no possible answer from this thing which is the Other anymore — this Other is just the totality of social relations, and there is no reason why the totality of social relations would have an answer for why it should specifically love any random subject, eg William A. Brown from Wilmington, Delaware. 
        </p>
        <p>
        The goal of the Lacanian therapeutic process is to abandon the endless quest of desire by “reinscribing desire back into drive”. What does this mean? Because there is not actually this role anyone can play which will guarantee the Other’s love for him, one should reject the quest posited by one’s desire — this desire for the love of the Other — as illusory. However, this does not mean the yearning associated with this quest it can be vanished, evaporated, done away with. It nevertheless is felt. It is inescapable that each subject must discover a unique strategy to present himself to the world as a person with passions and needs. It is also inescapable that the uniqueness of each person comes from the psychosexual complex developed in early childhood — this complex can never be extracted out of the subject like a tumor, as it is the foundation for his personality (the best each person can do is “become familiar with how he works”).  But there will never be a moment where the Other is able to see this inner core of the subject’s personality and give some kind of answer to the subject explaining to him what his duty to the Other truly is — because the Other is a dead and absent skeleton of God which can give no answers.
        </p>
        <p>
        The best the subject can do is re-interpret his quest to discover his duty for the Other as a <i>duty towards himself</i> — the idea that the Other is capable of loving the subject is an illusion, but an illusion that can never be done away with, because it comes from the innermost core of the subject’s personality. There is nowhere else the subject can possibly turn to discover how he is meant to develop himself in the world or what his role can be, than within his secret shameful psychosexual complex — it is the only thing he can cling to, his only true rock in the world, the birthmark which will never leave him. Over and over, he must satisfy the inner demand to give to the Other what is expected from his complex, and thus give himself and his personality to the world, but the movement of this now becomes one of endless repetition, a return to the same primordial experience again and again, rather than a quest of infinite yearning for a missing answer — this quest for an answer, the quest of asking the Other who the subject is meant to be to guarantee the Other’s love — is the quest which must be seen as futile. Our only hope is that in acknowledging the futility of the quest, yet continuing to traverse its path again and again as his daily task, the subject becomes happy like Sisyphus.
        </p>
        <p>
        The Lacanian cure is the logical endpoint of Nietzschean philosophy because it responds to the death of God in the same way as Nietzsche does — Nietzsche feels that now that Abrahamic religion has run its course and exhausted itself, we must extract ourselves from the vestigial “slave morality” the legacy of Christianity inspires in us, and figure out how to return to a pre-Abrahamic pagan “master morality” while incorporating the things we have learned along the way. The same is happening in the Lacanian cure, when the subject tries to reinscribe his desire back into drive. While he is following his quest posited by desire, seeking the love of the Other, the subject is the Other’s slave — attempting to give himself totally to the Other, in a one-sided relation, trembling against the fear of eternal judgment, the terror that he would fail to play the role the Other wants of him, a role which is never developed in its entirety. In fact, this role is not possible to play, because it does not exist, and thus the subject’s quest to discover it is in vain — there is no “gap in the world” which God has created for the subject, in which he can comfortably slip.
        </p>
        <p>
        The subject finds his “master morality” when he realizes that his desire to serve the Other is just an extension of his innermost self. At this point, his sense of duty becomes a repetitive, circular motion as he returns to the original kernel of his being again and again to discover the next step he must take to play his part in life, rather than looking for an answer externally — this is Nietzsche’s “eternal return”. The pagan warrior does not seek to be embraced by a smiling and weeping God in an ecstatic triumph but rather returns again and again to his site of originary trauma. The pagan warrior re-enacts the original trauma of his fear of God through sacrifice, sacrificing cattle or oxen to God, and in doing so temporarily recovering his lost <i>mana</i>. The ascended Lacanian subject does the same — he returns to his original trauma of his psychosexual complex again and again to discover the source of his being, and in doing so brings back an element of his lost power, becoming stronger in himself.
        </p>
        <p>
        In the move from desire to drive — there is a relation here to Deleuze’s interpretation of Nietzsche as a heretical Kantian. Kant told his reader that one should “will only that will which can become a law”. But Deleuze suggests that this is merely a <i>particular</i> case of what Nietzsche calls the eternal return, which is the imperative “will what can only be willed again and again and again”. Kant exists in the world of duty — the world of slave morality — trembling before a God who might cast him in the abyss if his will fails to coincide with an enveloping universal law. Nietzsche, on the other hand, understands that there is no universal law or duty to be discovered anywhere; rather, everyone is always establishing his own particular “universal” law — it is merely a matter of his commitment, of making the same decision again and again and again.
        </p>
        <p>
        Žižek defines “Gnosticism” as “the re-inscription of Christianity back into paganism”. In the Gnostic sects of antiquity in the first two centuries after Christ, Jesus was imagined to be a kind of alchemical master who is able to grant his followers power over nature and sexuality, rather than, as the orthodox tradition would eventually develop, a God primarily defined by his self-sacrifice who asks others to sacrifice themselves for him in turn. If the reader has followed the argument established thus far, he should understand why both Nietzsche and Lacan should be considered to be “gnostics”. The Gnostic credo is like Aleister Crowley’s statement “Do what thou wilt is the whole of the Law” — this should not be understood as releasing the subject from  Law and allowing him to follow arbitrary immediate pleasures, but rather it acknowledges that his fear before the Law itself is an expression of his truest inner will, a will which holds the Law within it yet goes around and beyond it.
        </p>
        <p>
        Lacan famously makes the pairing: Kant with Sade, declaring that “Sade is the truth of Kant”. Žižek points out that this comparison of Lacan’s is widely misunderstood. The vulgar, “obvious” interpretation is to imagine that Lacan is decrying Kant as a sadist. Here, we instinctively agree: Kant is this bastard, this cop-like character, by virtue of establishing this universal Moral Law that we are expected to cling to: it seems to us like Kant’s authoritarianism in this regard must stem from a cruel desire to punish those who do not obey him. This may or may not be true, but this is not Lacan’s point. It is not that Kant is a sadist, but rather it is that by understanding psychoanalysis it is possible to redeem Sade — we need to understand how Sade, on the other hand, is a Kantian — <i>a good Kantian</i>, who is obeying his duty.
        </p>
        <p>
        Kant says that we must will only what is willed by the moral law. But where is the moral law? It is not written outside of us. Were someone to try to discern exactly what was prescribed in all cases by the laws and jurisdictions of his society and then follow them to the letter, he would inevitably appear to be the most insane and perverted person — we are all familiar with the ways it is possible to “disobey the law by following it to the letter”. The true moral law is a reconciliation between what society prescribes for us and what our inner moral conscience deems to be correct. But from where does our inner conscience come from? Our inner being, which, as discussed above, holds our perverted and shameful sexual desires.
        </p>
        <p>
        But, crucially, Lacan’s point is that our inner being not only <i>may</i> prescribe violations of the outer law to us, but it actually <i>must</i> violate it. Everyone’s sexual fantasy necessarily includes the idea that it is a violation of the law — we can only get off if the sex feels dirty or wrong in some way. In sex, we want to descend directly into the other person and become one with them; this is the ecstasy we crave. To do this, the Other must be removed, because the Other is the conceptual “condom” which mediates all interactions between human beings and prevents them from falling into each other and dissolving against each other’s flesh. 
        </p>
        <p>
        But, because the Other is the structure which holds meaning, if the Other were to totally vanish, sex would have no meaning — mediation would vanish, but only for the sake of this disgusting animal flapping of body parts rubbing against each other. Therefore, the essence of sex has to be in the action that the Other comprehends but does not endorse. It has to be the “tolerated sin” — the exception to or suspension of the Law which grounds the ability for the Law to function. For sex to be possible, the Other needs to be present, but with its back turned. The Other must trust the lovers enough to say “Just for now, I don’t need to know what it is you are getting up to!” But this secret point of accepted sin which is the inner betrayal of the outer Law yet is necessary for its work is different from person to person — the place where we inevitably sin in the course of our duty in making our sex “dirty” enough to enjoy it — it is unbeknownst to one another, or even fully to ourselves, being the kernel of the unconscious.
        </p>
        <p>
        Therefore, the full perfect coincidence of the outer Law with its inner exception can only be something like the experience of Sade’s where it is both totally consummated and inscribed within fantasy. Sade describes the law out loud while raping the women in his boudoir. As such, he obeys the law by being its advocate, while horrifically violating its spirit by tormenting its subjects. Masterfully, he fulfills the law of his world, while at the exact same time manifesting the inner duty of his being — which is to experience the forbidden fruit of his pleasure; his joy in torture.
        </p>
		<h3>4</h3>
		<p>
        This detour through the ontology of psychoanalytic desire is not even necessary to prove that Sade is a good Kantian who has done his duty. From our modern perspective, it should be entirely clear that he is.
        </p>
		<p>
        The artist has the duty to create sublime aesthetic art. By raping women and writing about it, it is clear that Sade has fulfilled this, as his experiences led to the creation of art which is agreed upon to be absolutely canonical, universally considered important. Therefore his actions are “morally correct” at least for today’s morality which excuses abuse if it is done in the service of creating great art, eg in the case of a genius like Kanye West enforcing bizarre working conditions on his employees — you can’t make an omelette without breaking a few eggs, they say. (Though “woke” morality has made this excusing stance towards abusive geniuses less popular to express publicly lately, in my experience most people seriously embedded in the creative spheres will agree to it in private.)
        </p>
		<p>
        William Blake was able to turn poetry into a religious gospel by holding to the claim that the Imagination has an intrinsically redemptive and divine quality. Throughout Blake’s corpus, he invents a remarkable depth of insight into psychic economy, in a manner which parallels later insights of fields like psychoanalysis and post-structuralism, albeit in a self-invented schizophrenic dialect which resists interpretation. 
        </p>
		<p>
        Blake is aware that poetic visions are driven by poets’ sexualities, but thinks there is a way for the poet to work through his sexual material and come out on the other side into divine vision, and condemns poets who fail to do this and make art which is caught up in their sexuality. (This led Camille Paglia in her book <i>Sexual Personae</i> to describe Blake as a homosexual poet because there is no erotic sentiment towards women in his poetry. She seems to have not read or not understood the sections in Blake where he describes his deliberate reasons for avoiding eroticism in his aesthetics. He is heterosexual, but merely a prude.)		
        </p>
		<p>
        Blake uses a self-invented term “Emanation” to describe what is essentially the Other as object of sexual desire — his poetry describes how people are constantly unknowingly doing wrong because they are led about by their Emanation. Blake’s formative experience occurred when at the age of eight he saw an apparition of an angel in his family’s garden. He told his father, who beat him and instructed him not to tell lies, until his mother intervened on his behalf. Though he would remain loyal to the experience of seeing the angel and the religious quest it prompted, it seems from his poetry he would eventually determine that the hallucination of a beautiful young girl was his Emanation, an outward projection of his libidinal desire.	</p>
		<p>
        <i>Jerusalem</i>, Blake’s longest epic poem and the culmination of his work, ends with the following stanza: “<i>All human forms identified, even Tree, Metal, Earth & Stone, all Human Forms identified, living, going forth, & returning wearied Into the Planetary lives of Years, Months, Days, & Hours, reposing And then Awakening into his Bosom in the Life of Immortality. And I heard the Name of their Emanations: they are named Jerusalem.</i>” 
        </p>
        <p>
        The logic of Blake’s faith towards a religious utopian communism achieved through Art seems to be expressed here: Jerusalem, or the heavenly kingdom, is the sum total of all human Emanations, once they have passed through sexuality and become desire for the divine. If each human endeavors to discover his truest desire, it can only culminate in one wish — that all other humans would be able to discover and actualize their own desire as well, in a perfected community.
        </p>
        <p>
        But this dream of a chorus of unison would not come to past. Romantic artists in the following century would not take on this religious zeal — they would remain “devils” in the truer sense, embracing their sensuality, not passing through sexuality but remaining within it, rebels without a cause, dwelling in morbidity and decadence. It is like Blake is a kind of “Kant of the Imagination”, willing only what can be universalized. But one suspects that the intensity and fervor of duty to this universalism, in the case of both Blake and Kant, can only be achieved by its visionary founder. Those who attempt to create the wake have to deviate from the plan, propose some kind of Lucretian swerve, in order to exist as independent voices at all.
        </p>
        <p>
        Wagner provides a clear example of romantic morbidity, being the visionary who represents the zenith of the “art for art’s sake” romantic period of the nineteenth century. Most of Wagner’s operas give testimony to a kind of striving for mythic and religious ecstasy, but one which is trapped within a sexual deadlock. This is why Nietzsche would eventually condemn Wagner as being almost entirely caught up in his own hysteria, producing nothing but an impotent expression of his unresolved emotional and sexual problems. Wagnerian protagonists are caught in the struggle where they want to love a woman, but in order to love her, the entire world must be abolished first. <i>Tristan and Isolde</i> want to find unity in love but can attain it only in death — as they do so, the world around them falls into chaos, wrecked by the lovers’ passions.
        </p>
        <p>
        The artist experiences the feeling that the achievement of his Sublime, the culmination of his fantasy and his being, can only occur in a kind of moment where the reality which oppresses him is abolished and his inner self is finally actualized, or completed, in an yet-inconceivable way which would sever him from the world and its laws. Thus, the Romantic yearning for the Sublime is experienced like a yearning for death, not unlike the Christian believer who yearns for unity with his God which can only be achieved in the afterlife.
        </p>
        <p>
        One modernist composer Alexander Scriabin working in the wake of Wagner had the ambition to culminate his life’s work with a multimedia art piece which he would perform in the Himalayas, which he believed would usher in armageddon by achieving a perfect synthesis of all arts. The fantasy that there would be an end to the world following the artistic achievement is perhaps necessary to prevent the artist from confronting the inevitability of experiencing what Wagner did at Bayreuth — the despair upon the work’s achievement and its estrangement from the artist’s will and the gap from his  expectations.
        </p>
        <p>
        In the twentieth century, Georges Bataille presented in philosophical and poetic form an explication of the union of art, religion, fantasy, and death. Bataille depicts a world in which daily, mundane activity involves the build-up of energetic resources, the endless rhythm of which is redeemed only by divine experience in which what has built up can be <i>spent</i>, the experience of which reveals the meaning of life. Bataille praises festivals of excess, orgies, Aztec rites of mass human sacrifice, among other things, as moments of expenditure. The artist, particularly in these kinds of high Wagnerian spectacles, is he who endures his entire life laboring and building up the talent and the resources to create an ecstatic moment of presenting his Sublime vision to the world. In doing so, and giving the vision over to the world, he spends himself — giving himself over in a kind of spiritual death by handing over the thing he has held most precious, to those who will never truly know its value or care for it like he did. The artist’s duty is the duty to the perfection of his own apotheosis through self-expulsion. Every monumental artwork is like an underscored version of Mishima’s final act of seppuku. 
        </p>
        <p>
        If Blake is like the “Kant of the Imagination”, then Bataille might be the “Nietzsche of the Imagination”  — both Blake and Bataille agree that the artistic impulse always culminates in apocalypse and revelation, but in the former case, it is universal, and one of planetary harmony — in the latter it is personal, and distinguished in its importance through the height of intensity it is able to reach.
        </p>
        <p>
        There is a figure from fifteenth century France who inspires perennial fascination amongst those fascinated with art and excess, Bataille especially — one Gilles de Rais, a nobleman who fought in the Hundred Years War directly alongside the Christian saint Joan of Arc. De Rais seems to have had the most excellent and impeccable character for his first twenty-six years of life, gaining a reputation as a particularly valiant and heroic warrior for the divine cause. However, upon experiencing the burning at the stake of his comrade-in-arms Joan of Arc, Gilles de Rais abandoned the war effort and began squandering his large inherited fortune. He ordered his army of men to seize by force a church in Saint-Étienne-de-Mer-Morte to occupy himself in; an appalling act of sacrilege. Within the following year, local authorities investigating the disappearances of local children pieced together the aftermath horrific crime spree. De Rais would eventually be convicted of the rape and murder of over one hundred and forty children, giving him the dubious honor today of “history’s first serial killer”.
        </p>
        <p>
        The fascination towards the Gilles de Rais story lies in the suspicion: what if he was not a good Christian who then “switched sides” to the Devil out of despair, inspiring his crimes? Is this excuse is all too easy? Rather, one has the dreadful sense that De Rais was “loyal to God the whole time” — Bataille gives him the title of a “sacred monster”.
        </p>
        <p>
        Perhaps the voice urging de Rais to kill was not a Christian God, perhaps a kind of strange God of private gnosis, but it is as if the holy angel told De Rais to serve him by valiantly march alongside the Christian warriors. And yet upon the his faction’s defeat, the only way to serve this God became to make a private spectacle of horror of the world — a shrine of mangled bodies — to slaughter one innocent on this temple after another, punishment for the failure to win war in the angel’s name, a regress to primordial displays of sacrifice.
        </p>
        <p>
        In a certain sense, in modernity, are we not all like Gilles de Rais? That is: as Western subjects engaged with the arts, consumers of the would-be sublime, have we not all experienced this abandonment of religious duty for delight in desecration? While our desire to experience the sublime began in the Middle Ages as faithful Christian religiosity, a traumatic rupture happened in which God left us, and now we experience the sublime in more and more intense reminders of our abandonment and destitution — the well-known ecstatic trance when staring at a Rothko painting.
        </p>
        <p>
        The zenith of modernist artistic production can perhaps be considered to be today’s film industry. The growing rumor, reverberating through the world after the scandals of Epstein, Weinstein, Diddy, is that Hollywood is deep in the clutches of “satanic pedophiles”. Increasing amounts of evidence comes to light to suggest that the more paranoid imaginations of the darkness lurking within Hollywood might not be so far-fetched. But of course, we know that Hollywood and industry “child sacrifice” is certainly real as a metaphor — it is a monster of lights and engineering which devours the youth. We experience the terror and the joy of the Sublime as we watch young boys and girls surrender themselves over to the production of our collective fantasy, sacrificing their lives to this altar of Art. We promise apotheoses to martyrs like Jimi Hendrix, Kurt Cobain, Lil Peep, xxxtentacion, Juice WRLD; the younger and the more beautiful the corpse, the more perfect the offering.
        </p>
        <p>
        What can be done to reconcile these problems here? The absolute worst gesture at this juncture would be to suggest that a solution is immediately likely or plausible. The death of God cannot be resolved by a gesture so naive as “choosing to believe in God”, as this merely re-establishes a subjective faith to take up as an individual crusade, a personal gnosis like that of Blake or Wagner or Bataille or whoever else, and does nothing to resolve the fact that the ground of social existence is a kind of graveyard to play in.
        </p>
        <p>
        It is not a matter of personal or subjective will. Unless, like a sudden apparition of a flying castle in the sky, an objective structure reveals itself for the artist to submit himself to, knowing it to be his duty — there is no escape from the walls of his subjective prison of inner desire, he must bounce around within this hollow castle again and again, pounding his own body against the earth to follow his own disturbed quest to the strangest and emptiest places, knowing of no other way.
        </p>
		<div><a href="/">← Home</a></div>
    </div>
		
  )
}

export const Head: HeadFC = () => <title>Art and Duty</title>

export default CSVSPage

