import * as React from "react"
import type { HeadFC, PageProps } from "gatsby"
import "../index.scss"

const CSVSPage: React.FC<PageProps> = () => {
  return (
    <div className="container">
    <h1>Just to state the obvious, Elon’s takeover of Twitter is a major historical event</h1>
		<div><a href="/">← Home</a></div>
		<p>
		These past few weeks, the main spectacle on X app has been watching <a href="https://twitter.com/whstancil">a progressive policy analyst named Will Stancil</a> incite hordes of race-and-IQ posters to set themselves against him in a protracted flamewar which shows no sign of ending. Though people both opposed to and sympathetic to Stancil are warning him that he’s really playing with fire here in antagonizing this salivating mob formation, he seems to be content to continue this indefinitely — I wouldn’t be surprised if months later he is still doing this; it will have become his new “brand”.
		</p>
		<p>
		Stancil’s goal seems to not so much to muck into the epistemology of science around the race-and-IQ studies, but <a href="https://twitter.com/whstancil/status/1751269080965824765">to highlight to the world that the people he’s arguing with exist, there are lots of them, and they are “Nazis”</a>. Among my frustrations with this debate, it is irritating how Stancil insists on framing this in a crude and inaccurate way (They are ‘Nazis’? As in they are members of the National Socialist German Worker’s Party? Why not just be satisfied to say they are racists, if this is what he means?) However his basic contention is obviously correct: that there is this huge contingent of people on X who are racist in a politicized and aggressive way and are using this “scientific” argument to advance their views while posing as if they care about science in the broad sense rather than their race agenda.		</p>
		<p>
		<a href="https://twitter.com/whstancil/status/1759574862249578925">Stancil seems to think that his mission on X is</a> to fill in gaps in the liberal media’s ability to report on events in a way which yields the narrative the Democrats need. He seems to have picked up on something fundamentally true and strange, which is despite the fact that, starting from the rise of Trump and the alt-right in 2015, there has been this whole journalistic apparatus of obsessively crawling through corners of the internet to report on developments in racial extremism & etc, they have been mostly quiet about the dramatic shift in discourse happening on X in their faces which Elon has engineered. 		
		</p>
		<p>
		<a href="https://twitter.com/whstancil/status/1754022774320795954">As Stancil points out</a>, liberals will repeat these various cliches of denial — “I’m pretty sure Elon just likes memes dude”, “you know Twitter isn’t real right?” People who say these things should be mocked for being stupid. Or they don’t pay enough attention to X to see the new discursive developments, which is good for them, but then they should stop talking about things they don’t know about. 		</p>
		<h3>Is Twitter real?</h3>
		<p>
		That’s the big question we have to get into first — is Twitter, or X, “real”?
		</p>
		<p>
		Something I have noticed recently when talking to people in the class of social media adjacent content production is they will try to form extremely rapid shifts in contexts between whether various statements and postures are “serious” or “real”.
		</p>
		<p>
		From this class, the insistence that X cannot be “real” is like a mechanism of warding off a psychosis which seems to be intrinsic to using the app. In X, there is no way that one can somehow get a sense of the panoply of discourse and where you are situated in it; everything is served “For You” as if you are the center of the world. If you set off some beehive and are flooded with nonstop notifications you feel as if you are truly being besieged by the world itself, at which point you will have to “log off and touch grass” to get a sense of perspective. Even Elon himself seems to be as enmeshed in this psychosis as his users; he gets drawn into foolish debates on the timeline too and there is little system or method to his posting.
		</p>
		<p>
		However, there is a larger form of the denial of Twitter’s importance which extends beyond the class of its users. This is the mantra-like insistence that “the internet is not real life”. Even after the internet cults of wokeness and Trumpism have torn through institutions, it is repeated that these cultural surges are not “serious”. And indeed they have been ridiculous. But at this point it is clear that they are major historical events, the ultimate consequences of which are still not known.
		</p>
		<p>
		To not analyze these events and movements is to abandon oneself to a nihilism of experience in which we as digital subjects are forever swimming in a soup of non-interpretability from which no clarity can ever be forged. Perhaps in the long run (deepfakes, etc) this will become actually true and inevitable. I suppose my contention is that it is not quite time to resign ourselves to this just yet. Actually right now could be the most important time to resist this.
		</p>
		<p>
		There is a fundamental contradiction the explorer of the internet must have in mind
		</p>
		<p>
		1. As the famous banner on 4chan once said: anything online should at first be assumed to be a creative work of fiction with no depth, a pure simulacra in a theater of play. But then, in some cases, it is deep — sometimes a disturbed person who got radicalized by online race content posts his manifesto on 8chan and everyone thinks it’s “bait”, but the next day he kills thirty people.
		</p>
		<p>
		2. Nevertheless, the culture created by this play in which both deep and shallow signs are mixed, has ramifications on real life downstream from it.
		</p>
		<p>
		The sadly difficult part is that you don’t actually know what is or isn’t “real” online until you look into it. For example, some people will remember <a href="https://cuteness.substack.com/p/lets-all-love-miya">in 2019 there was this Twitter movement called KaliAcc</a> which was promoted by two posters, Miya and Sunny. They had a style of extreme shock posting that involved neo-Nazism, bragging about abusing people, and this whole other bit about wanting to groom impressionable teenagers into becoming trans. I couldn’t tell at the time if it was an actual violent cult of transsexual Nazis, or an art project, or what was going on. As it turned out, it was half and half — the two collaborators did not see it the same way. Sunny, on the one hand, was eventually revealed to be a femboy living at an actual neo-Nazi commune somewhere (apparently this is a common thing — the neo-Nazis can’t get any cis women to hang out with them, so oftentimes one of them takes one for the team and goes on HRT so the others have a path to gratification). Miya on the other hand turned out to be a <a href="https://goldenlight.mirror.xyz/AOaPt55Uz0X4PEOPWtL7Iv6djVD7bq-GYDF-_lq_iGA">conniving brown art kid</a> who was interested in precisely this question of the impossibility of figuring out the reality behind the internet and making sense of it — and eventually made millions off of the art he created through cryptocurrency.
		</p>
		<p>
		So the point is you don’t know how serious anything is or if there’s any reality behind the sign, unless you’re willing to investigate. The frustrating thing is dealing with people who don’t understand this. They imagine their own stupidity to be a kind of learned wisdom. “Oh you are being silly, of course nothing on the internet is real, it’s all just one big joke, everyone knows this” on the one hand, and on the other “oh, my sweet summer child, you don’t think abuse/fascism/whatever is a real thing, you don’t think all these malicious people hide behind jokes?” Actually, the only truly naive position is to smugly believe you can know any of this a priori from the outset, to not understand that there are simultaneously both jokesters and serious actors, intermingled in all of this. There is shallowness, and there is depth.
		</p>
		<h3>Elon, Twitter and history</h3>
		<p>
		The other aspect of “Twitter is not real life”, coming from more established pre-Twitter media people, is a repressive denial of the disturbing fact that Twitter has become the “hottest”, most “upstream” medium in the West, radically displacing television and legacy media, forcing those other platforms to constantly react to whatever is happening on Twitter and play catch-up to its discourse.
		</p>
		<p>
		This is disturbing and tragic because it’s obvious that Twitter is bad for us and plays to our worst impulses. The whole concept of the site is based around shortening our attention spans — you literally cannot make a nuanced argument on there, because 280 characters is not enough room for nuance.			
		</p>
		<p>
		As McLuhan says, the medium is the message, and whatever ends up as the “hottest” media format usually ends up radically reshaping the very form of our subjectivity in profound and subtle ways. We are not the same after Twitter as we were before Twitter, even in our private moments, in silence. Those who get sucked into Twitter frequently post their fantasies of one day “logging off forever” — returning to a time of innocence — but they never do. They wax nostalgically about the elysian 90s, in which one went to Blockbuster to rent VHS tapes, had to ask the clerk at the record store for CD recommendations. Back when media experiences occurred in discrete packages, before it was a sea of continuous turbulence one thrashes about it constantly. 	
		</p>
		<p>
		However, McLuhan had the luxury of being able to analyze shifts in the technological environment which occurred over the span of decades. What we have now is a constant shift of dominant modes of communication, with various consequences. Wokeness famously emerged first on Tumblr, but now no one uses Tumblr anymore. These platforms appear and disappear suddenly and for whimsical reasons, such as the actions of a single capitalist. Actually this is mostly what I am interested in analyzing — the way the specific effects of the fluctuating media environment are shaping our contemporary subjectivity (ie, there is a psychosis proper to Twitter that is different than the psychosis of Reddit, the psychosis of Instagram). This post is going to be touching some aspects of this surface.
		</p>
		<p>
		It should be remembered that the actual impetus for Elon buying Twitter was, originally, a response to this profound <i>irresponsibility</i> within its central role of discourse production. That is to say, Elon promised “to give the people free speech”, rather than the status quo of a kind of bureaucratic anarchy in which an elaborate system of moderation would ban people (mostly right-wingers) with no warning, clear rules, or ability to appeal. Insofar as Twitter is today’s “public square” for political discourse, the argument goes, it must be neutral, approached like a utility, otherwise this severely problematizes the premise of liberal democracy with its right to free expression.
		</p>
		<p>
		I’ll admit that I got this one totally wrong. At the time when Elon was first making the deal, all these dissident right accounts were getting excited, asking “is Elon our guy?”, fantasizing about being able to say as many racial slurs as they wanted under a new regime. I remember kind of making fun of them, telling them “you guys have a savior complex, you’re always looking for a daddy, Trump wasn’t your daddy, Elon won’t be either, nothing is going to change”. I was wrong — Elon totally is their daddy — things have changed.
		</p>
		<p>
		Elon has not of course replaced the incoherent policy with a coherent one of free speech. There is still arbitrary banning with no clear logic, seemingly often targeted at the left particularly for being pro-Palestine. Elon for instance has said he would ban leftists for saying <a href="https://www.thedailybeast.com/elon-musks-feelings-led-him-to-censor-legal-speech-on-x">“decolonization”</a> or <a href="https://www.forbes.com/sites/kimelsesser/2023/07/02/elon-musk-deems-cis-a-twitter-slurheres-why-its-is-so-polarizing/?sh=4f2c5f2e4ac6">“cisgender”</a>. Like in Russia, the revolution has gone bad — it turns out the glorious freedom promised under the new order would be the freedom of the sovereign to act arbitrarily and with absolute power as the exalted holder of the people’s will. The people, it would seem, according to Elon, want <a href="https://variety.com/2023/digital/news/elon-musk-twitter-logo-doge-dogecoin-meme-1235572343/">the bird logo to be changed to the doge face</a>, or for the sign on the Twitter building to have <a href="https://fortune.com/2023/04/11/elon-musk-twitter-offices-sign-painted-white-w/">a letter removed so it says “Titter”</a> — the people demand Elon meme more and more epically.
		</p>
		<p>
		Now — in no uncertain terms, Elon’s takeover of Twitter must be seen as nakedly political. He himself has said that <a href="https://www.telegraph.co.uk/world-news/2023/09/01/elon-musk-reveals-twitter-takeover-hatred-woke-mind-virus/">his motive in purchasing Twitter was to stop “wokeness” at its supposed source</a>, for fear that it would lead to communism.
		</p>
		<p>
		The most visible and drastic change Elon made was the dethroning of the bluechecks. Prior to the takeover, you could get a bluecheck if you were part of the credentialed media class. As I think Elon himself might have pointed out, this was a deeply hypocritical system, because the ostensible purpose was to verify a user, ie to indicate that they checked his ID and he is who he says he is, but then they added a criteria of “notability”, which made the bluecheck — literally — a status symbol. When Elon took over, he instead made Twitter a pay-to-play system in which you can pay $8 a month to get a bluecheck and your posts get boosted in the algorithm. On top of this, there was a dynamic where all the credentialed media people refused to get the new bluecheck and many left the site entirely, due to their mutual antagonism with Elon. So the bluecheck began to represent a badge of loyalty to Elon and his agenda — therefore making the views of those who are loyal to him spread further across the site.
		</p>
		<p>
		<a href="https://graymirror.substack.com/p/the-twitter-coup">Curtis Yarvin wrote that Elon’s dethroning of the bluechecks represented a regime change</a>, and was a model for the reactionary regime change he would like to see in America. This is certainly what it felt like — the uncanniness of this shift between the new and old guard is like some tyrant taking over and purging all the bureaucrats and intellectuals and then dressing up his drooling thugs in their ill-fitting uniforms — a total parody of the authority which they have replaced. What the new bluechecks do now is they write these long threads they researched from Wikipedia in a pompous authoritative tone about some lowest-common-denominator right-wing talking point and get hundreds of thousands of followers very quickly under the new algorithm. 
		</p>
		<p>
		Of course it’s not to say that the old elite was not decadent and horrible and corrupt in their own ways, but it’s going to be clear that these new forces rushing into the vacuum are going to lead us somewhere even more depraved.
		</p>
		<p>
		There isn’t really any way to point to a datum that objectively demonstrates this, but many people have remarked that there is a change under Elon’s algorithm where a post either does or doesn’t take off — if it doesn’t get a bunch of likes quickly no one will see it, not even your followers. You have no choice now but to craft “engagement bait”, a little more deliberately than you were doing before, or no one will see it. Your words must please Elon! If it does not please Elon, why even speak?
		</p>
		<p>
		Then, the final element of the structure here is: you can now get paid if you make a post which generates lots of impressions. What gets impressions is determined by Elon’s algorithm. So in a sense, Elon has turned the entire website into a paid essay-writing contest for the type of racist populist propaganda he wants to see more of in the world. Now, if you are <a href="https://twitter.com/whstancil/status/1689419663300587522">this type of person, eagerly writing threads on race-and-IQ studies in the hopes that the new algorithm boosts you</a>, the greatest thing that can happen to you is that Elon himself could appear in your comments, like your post, even re-X you. Thus forms this dialectic between the sovereign and the people for whom he speaks.
		</p>
		<p>
		It might be that some other thing happens soon to disrupt this trajectory — maybe the board ousts Elon over a baroque corporate drama — the world is fundamentally unpredictable. Or, it may be that Elon truly represents something new — the resolution to a kind of crisis, the crisis of digital memetic production, this trauma in the fabric of discourse, which can only be resolved in the form of a sovereign. The history of experimentation amongst social media platforms — a history which is not represented, felt to be not “real” — is that of trending towards Twitter as its telos, the tweet as a perfected form like the BigMac or an iPhone. Certainly all other social media platforms have fallen by the wayside. There is only one Twitter — now X. And its limp competitors: BlueSky, Mastodon, Truth Social, whatever, are only trying to copy it. Twitter is the culmination of the digital form. But then, it presents a problem to the world by being a site of this bureaucratic anarchy — which, history is now showing us, can only be resolved through the introduction of a sovereign, with his cult of personality, his arbitrariness and inconsistency, the anarchy of bureaucratic dysfunction replaced with the anarchy of one man’s personal will.
		</p>
		<p>
		A lot of people seem to have trouble parsing Elon’s politics. There is often this inability to think beyond a crude linear model of the left-right spectrum: “well on the one hand he’s always had this really strong ‘I fucking love science’ Reddit centrist-y vibe, but on the other hand he does sometimes have this thing with the far right, I’m not sure what’s up with that”. My stance is that all you have to do to make sense of Elon’s politics is remember that he’s South African. He seems to not ultimately think about sociopolitical issues other than what gets in the way of building his rockets, but is racist because he has this fear of a black and brown underclass potentially swarming and overtaking the machinery the white capitalists are trying to build. That’s my read on it at least — that’s what I think he means when he says things like <a href="https://twitter.com/elonmusk/status/1527356085090545664?lang=en">unless it is stopped, the woke mind virus will destroy civilization and humanity will never reached (sic) Mars</a>”. Wouldn’t he simply explain what he meant every time he invoked “wokeness” — if the point he was making wasn’t this basic one that is obscene and unutterable?
		</p>
		<p>
		The big picture here is like this. There is this delicate yet gradually rising open alliance between tech capitalists and the dissident right, which is a break from the norm of what we are used to. These kind of run-of-the mill progressive critics analyze this in the context of the familiar, of the 20th century — “oh well of course they are right wing now, they want tax cuts, they hate the poor, they’re going mask off”. What is missing from this analysis is the possibility of the new; a rupture — the specter that the tech elite could become a truly revolutionary class which in some way or another displaces the state.
		</p>
		<p>
		This is the thesis of the neoreactionary movement which has come into greater and greater bloom across the past decade. With a victory like Uber, for instance, you can see how the tech class through brute force displaced a bureaucratic system of taxi medallions through designing a superior system with a better interface — Uber was illegal when it was first created; its creators were gambling that the regulators wouldn’t be able to keep up. As the saying “software eats everything” goes, it is not inconceivable that this kind of thing could happen to almost every system in our lives, especially with the advent of strong artificial intelligence. Curtis Yarvin and Nick Land, the two primary figureheads of neoreaction, each believe that Elon is “their guy” heroically carrying out in practice what they have in theory, and I believe they are very likely correct.
		</p>
		<p>
		The real imperative, as I see it, is to articulate a future for a world in which sovereignty does become increasingly displaced from nation-state bureaucracies into diffuse digital networks, which does not result in the annihilation of human potential. This nihilistic right-wing attitude at the vanguard of thinking through this technological transition is disturbing because it signals the abandonment of principles of justice which governance should be predicated upon, in favor of a brutish love for pure domination.
		</p>
		<p>
		When Walter Benjamin described fascism as the aestheticization of politics, he might have been far too optimistic. The new aesthetico-ideological consensus we see among the dissident right as its culmination is this Elonified reddito-fascism. Fascists will go on about this, oh we need beauty to inspire young men, cathedrals, pagan gods, lyric poetry, marble busts, but the ultimate triumph of this moment in the zeitgeist is just going to be the Reddit mascot and the Dogecoin mascot stomping on your face forever while an anime girl dances to keygen music. We see this same transition happening in Bukele’s El Salvador and Milei’s Argentina. People are so easily tricked by this Redditism that they thought there was some amazing confrontation <a href="https://www.cnbc.com/2024/01/17/argentina-president-javier-milei-urges-davos-elite-to-reject-socialism.html">when the “populist” Milei went to the “elitist” World Economic Forum and went on a tirade about how socialism is bad</a>. Look, Milei is a <a href="https://www.wsj.com/world/americas/argentina-votes-for-new-president-to-confront-economic-crisis-99b73b86">self-described anarcho-capitalist</a>, all his policies are to favor the wealthy accumulating more wealth, just because he says that and then says “flaming narwhal bacon egg and cheese big titties beep boop bop all your upvotes to the left bazinga” (imperfect translation from Spanish) and the masses can’t get enough of it, doesn’t mean he’s ultimately on their side.
		</p>
		<p>
		I actually like the music a lot, but Kanye West, vessel for the world-spirit that he is, has kind of provided an example of what the arrival of the reddito-fascist spirit could look like in art with his new album <i>Vultures 1</i>. The build-up to the album’s release made it seem as if Kanye was preparing for a kind of apocalyptic political confrontation, presenting himself as a black Christian <a href="https://www.timesofisrael.com/doubling-down-on-antisemitism-kanye-west-praises-hitler-in-unhinged-interview/">“Nazi”</a> at war with all existing systems, launching for instance <a href="https://www.yews.news/">a news site in which every article is paired with a William Blake excerpt</a>. The actual album however, not only basically lacks political or theological content, but also kind of discards any possible coherence with the conservative Christian cause Kanye had been championing by being full of obscene sexual lyrics from front to back. Socio-political vision has been traded for an hour-long celebration of vulgarity and chauvinism — the glorious volkisch revolution of faith seems to have been substituted with a piggish anti-wokeness. Probably the most indicative instance of the album’s sensibility comes on the song <i>Back to Me</i> when instead of writing a rap verse Kanye sings several times in the row a quote from a Jay and Silent Bob comedy “<i>beautiful big titty butt-naked women don’t just fall out of the sky you know!</i>”  — an epically meme-able, upvote-worthy moment if there ever was one. “<i>Elon, where my rocketship? It’s time to go home</i>”, Kanye asks on the album, aligning himself with the new sovereign’s ascendency. 
		</p>
		<p>
		Someone will say — oh, if you don’t like this vulgarity, just look away. If only it were so easy. This vulgarity is a kind of weapon. It is a poison that is set to seep into the cracks of everything. It is a missile system. This must become the nebulous target of any ideological critique today.
		</p>
		<h3>The impossibility of race realism</h3>
		<p>
		So, going back to the start of all this, the question I have is how far this race-and-IQ discourse is likely to go and if it will enter the mainstream — which would seem to be Elon’s goal by platforming it at scale. Chris Rufo, who is leading the race campaign from the center-right with enormous success, seems to have signaled that after his latest political victories against so-called critical race theory he is intending to promote the “hereditarian” thesis, so it could very well become a talking point soon and in the background of the 2024 election, with major crises around immigration looming.
		</p>
		<p>
		Okay, so, let us wade into what strikes me as some of the central epistemological paradoxes around this race debate. What I observed in the (non-)debate between Will Stancil and the race-and-IQ people was how totally inconceivable it was that the debate could resolve into positive knowledge, on a number of levels. There is a sense in which, even if a kind of truth could be gestured at by analyzing these studies, it would still be totally <i>unrepresentable</i>.
		</p>
		<p>
		For the anti-racist, such as Stancil, any idea of racial difference cannot be represented, because it is held to be obscene. Stancil for instance seems to find it obscene to make statements like <a href="https://twitter.com/whstancil/status/1754903643935866949">“Jews make a lot of money”</a>, even though this is both obviously true statistically in America and a compliment to Jews. So obviously he is not ever going to concede any ground — no “oh, yes, when you look at this study, you’re right that it could tentatively suggest that, nevertheless”, etc.
		</p>
		<p>
		But, more interestingly, the potential knowledge arrived at through the hereditarian hypothesis, cannot be positively represented by the racist <i>either</i>. Or at least this is the claim of the racist Bronze Age Pervert, <a href="https://twitter.com/bronzeagemantis/status/1742265449423810912">who has argued that while his followers should accept racist hereditarian conclusions amongst themselves, there is no way this can be turned into official ideology — rather, official ideology should be race-blind</a>. This is because no one will accept a sovereign telling him that he should be ruled on the basis of his own natural inferiority. Rather, a sovereign must flatter his subject, give him a narrative which redeems his inferior position somehow, etc.
		</p>
		<p>
		The fundamental thrust of it is that liberal democracy and other rational bureaucratic structures are grounded on the formal notion of a universal nature shared between all subjects. In Lacanian terms, universal equality is the symbolic order, and a sense of difference between people is the Real threatening to intrude upon its formal purity.
		</p>
		<p>
		The liberal order is an order of rational subjects using public reason to form a shared truth. But the true menace to the order of rational subjects is a subject who lacks reason, and lacking reason, cannot be convinced of his lack of reason, and thus must be excluded from participation through other means — innuendos, condescension, diversions. This is the figure of the madman. To Bronze Age Pervert, it would seem like the sufficiently low-IQ are in this very position of the madman: the feeble, the senile, the insane, all can perhaps be condescended to with similar delicacy.
		</p>
		<p>
		The Bronze Age Pervert’s Straussian position would seem to be: the rulers maintain a kind of noble lie of equality, while inwardly working to deny those they deem naturally inferior access to levers of power. From the perspective of the excluded inferior subject, this can only be seen as racial or class discrimination, an intricate conspiracy to limit his human potential which will nevertheless be continuously denied by those exerting it — it is that. 
		</p>
		<p>
		There is a sense in which “everyone is racist” is simply an analytic a priori. Expressive patterns across the different races differ, but as a liberal subject, I must be extremely reluctant to make judgments across these differences lest they intrude with the formal equality I am to treat my co-citizens with. But how are these judgments possible to avoid, given that there is difference? Say I have a great distaste for the music that Hispanics listen to, and prefer the music of blacks — naturally I will avoid events full of Hispanics playing music and go to the ones hosted by blacks — but I have to make sure this aversion to Hispanic social life does not creep into an aversion of Hispanics in general that would pollute some larger liberal obligation. (To be honest this isn’t a hypothetical at all; I really can’t stand Latin music — I think this might be the most racist thing about me — I’m looking forward to moving out of Bushwick soon in which Latin music plays from every moving car. And of course I’m obligated to say I’m sure if you really open your mind to it and get into it it must have its wealth of positive qualities...)
		</p>
		<p>
		There was this kind of Bush-era lull in American race relations which at this point in time represents a sort of “normalcy” people are hoping to return to. Back then, it was kind of the role of comedians and similar figures to gesture at the gradients of difference in a lighthearted way to give a kind of representation. If I’m in polite company with a bunch of bourgeois people I know from work and I say “have you ever noticed that when black people drive they sit like this but when white people drive they sit like that”, they’ll tense up and sweat, feeling as if I’ve said something obscene — a faux pas — but when some comedian like Dave Chapelle in his sanctioned social role says something similar, they love it and feel relieved.
		</p>
		<p>
		However in the wake of Black Lives Matter and so on the split in a person between unconscious perception of difference and conscious commitment to the formal order of non-difference seems to have been problematized. The truism of “everyone is racist” seems to have received the addendum of “and thus must fight a desperate inner struggle to become otherwise”. People now sell expensive therapeutic seminars on how you as a white bourgeois person can heal yourself from your original sin of deep-seated implicit racism. Obviously, this is a complete disaster, psychoanalytically speaking. To engage in this obsessive disavowal of difference, attempting to purge it from one’s mind totally, is to enact this crazy act of repression that can only culminate in the return of the repressed, which we are now seeing in the form of this white race reaction. The mature attitude is to be capable of holding two things in one’s mind simultaneously: politico-ethical commitments to universal objects, and awareness of difference.
		</p>
		<p>
		What is crazy about these race-and-IQ “hereditarian” people is that they are really into this “facts, science, rationality and logic” posture and as such seek an “objective” determination into this idea of natural difference. But this is obviously ridiculous. The whole “objective” position of the so-called social sciences is a grotesque farce. When one applies scientific judgments onto a human being, one is not making an “objective” judgment, because a human being is not an object. The judgment exists on an intersubjective plane. That is to say, obviously, if I am presenting a “scientific” perspective to suggest that a certain subject should be held as politically inferior, that subject is going to suddenly shoot up in his chair — “now hold on sir, can we look a little closer at this, how exactly are you getting this data”. In what possible world could the debate of how to interpret these studies ever resolve? The fantasy of the hereditarian is that we just need more and more “science”, to look closer and closer at genes and whatnot, as if you could dissect a black person with a scalpel thoroughly enough to determine and demonstrate precisely why there is black-on-black crime. It’s inane.
		</p>
		<p>
		Of course, the science stuff is a total red herring from the perspective of the racists. It’s likely that very few of them care at all about the actual social science epistemology. The point is to leverage the authoritative aura of data and so on to crack open the gap of representability in liberal subjects to orient them to racial difference. This is why <a href="https://twitter.com/Steve_Sailer">Steve Sailer</a> (the primary figure Will Stancil is arguing with) wrote a book called <i>Noticing</i> and not a book called <i>Doing Meta-Analyses on Demographic Data</i> or something like that — the goal is now that the online racists have permitted me to, I’m going to “notice” that the Vietnamese mothers on the playground don’t control their kids as well and think and gossip about it, or whatever, rather than forgetting about it or ignoring it. Thus the product of this discourse is not a new scientific object, but rather an increasing slippage between the socially ordained perspective of non-difference and people’s (perhaps increasing) sense of difference from their co-citizens. This racism is purely sort of a proliferation of a diffused cynicism, it is not a “new order” yet.
		</p>
		<p>
		Thus, the great irony of this “hereditarian” standpoint is this. They are all into this notion that trying to scientifically look for race differences and their supposed sources could get them to an objective truth. Some of them are probably naive and neurotic enough to actually believe that this could be possible. After performing some glorious genetic study, found like a gem plucked from a treasure chest, they imagine that we can lift the “fiction” of non-difference in a way which allows us to rationally talk about difference and thus fold it into the liberal order, rather than keeping it only in dirty jokes and out of the public conscious, which is to say unrepresentable. 
		</p>
		<p>
		But in fact, the only thing that seems likely to happen anytime soon is that race-and-IQ discourse on X will plunge the world and its discourse into a deeper level of dissimilitude. Which is to say, as it stands, “we know that the idea of non-difference is a social fiction”, but the next level of this is “we know that we all know that the idea of non-difference is a social fiction” — that is, everyone is learning to “notice”, everyone is permitting themselves to gossip among their friends and group chats about the racial differences they see, yet everyone would deny it if you asked them about it to their face. 
		</p>
		<p>
		Something like this seems to be happening in the Downtown NYC subculture. The hosts of the popular Red Scare podcast, who seem to have gone from once identifying as socialist to positioning themselves as far-right, helped curate an <a href="https://www.washingtonpost.com/style/fashion/2024/02/12/fashions-problematic-fave-is-elena-velez/">antebellum plantation-themed fashion ball</a> last week. This was presented as a salon to discuss the critical legacy of the novel <i>Gone With the Wind</i>. Now, if it was really intended to be this critical salon, the proper way to do it would be you present multiple perspectives in dialogue: maybe some woke person says the novel is this deeply bigoted document and should only be read through a deconstructionist lens, then some other person comes on and says no it has xyz redemptive quality that justifies its legacy as canonical. What actually happened was that several people praised the supposed feminism of the novel (strong female characters) and then Anna Khachiyan of Red Scare gestured to the subject she’s “not allowed to talk about” — race — because presumably her opinions on this issue are obscene. But the next day, she saved us some speculation by posting on X some hint to her actual opinion of black people by sarcastically writing <a href="https://twitter.com/annakhachiyan/status/1757233698166993284">“Maybe one of these African migrants will be the next Bach”</a>.
		</p>
		<p>
		Not going to bother with a Charlie-from-It’s-Always-Sunny-with-the-bulletin-board-style analysis but it seems pretty likely that this fashion party was organized in line with these political networks who are promoting the race reaction, under a fairly crude logic of wanting to normalize white supremacist gestures in upper class coastal society by seeing what they can get away with. I read somewhere that Steve Sailer himself happened to be at this party but I’m not sure if that’s actually true. However, despite these increasingly open racist provocations, those advancing them continue to deny any intentionality, seriousness, etc., to their gestures, defending themselves with gaslighting-y logic in the vein of “it’s weird that you would read anything into this”.
		</p>
		<p>
		So the race reaction moves increasingly into a position of open, disavowed conspiracy. Thus a thick fog of suspicion, deception, paranoia, and bad faith creeps through the canyons, winds around the tower, enters the town square, becomes the new mood of the day.
		</p>
		<h3>Clown world</h3>
		<p>
		It seems to me that as the general reactionary position advances and consolidates, it will only be able to do so through thoroughly suffusing the social sphere in a kind of fog of war —  this mood of paranoia, implied hostility, and confusion.
		</p>
		<p>
		I feel as if there is a kind of absolute horizon stretching before me of a new world which, once realized, could be impossible to escape from.
		</p>
		<p>
		The two faces of this essay meet here: the simulacra of the online and people’s insistence in its non-reality, and this new race discourse — because as demonstrated, the latter culminates in a thick mood of disavowed hostility. The type of thing that is happening on X is that some unfortunate black person will for whatever reason set off a group chat of highly politicized racists who will spam them with whatever crude racial trope you want to pick; monkeys, watermelons, and then when the victim gets angry the response will be “why can’t you black people take a joke” “log off and touch grass the internet isn’t real”. Trololololo. Obviously, this type of speech is very “real”.
		</p>
		<p>
		So this gets to the blatant contradiction in the pro-Elon thesis that by lifting censorship, he is restoring some kind of free public square, which is X. But the medium is the message. A free public discourse of writing letters, petitioning one’s senators, publishing editorials, presenting one’s opinion to others in these various ways, is not the same as the freedom to put on an avatar and send ambiguously threatening AI-generated images and cryptic in-jokes to people you dislike. The new freedom promised by Elon is not the freedom to participate in the rational order of liberal subjects, but the freedom to participate in the psychotic delirium of the simulacra and their play — this unwise adventure into the cybernetic which is affirmed by all of its participants as non-real, though reality is subordinated to it.
		</p>
		<p>
		The image of Elon as Caesar is perhaps revealing. The fall of the Roman Republic occurs precisely through the last-ditch attempt to save the dying republic, with Caesar as its hopeful savior. The parallel here is that Elon as the savior of the liberal public square is in fact its executioner — by removing the bluechecks, he has eliminated the last representatives of the rational order of liberal subjects, bound by their names, their professionalism, their fact-checking, etc., keeping us all in line through their incessant moralism, and instead plunged the productive center of Western discourse into a theater of combative play — the unreal world of the troll in which reason is impossible — the Empire of total dissimulation.
		</p>
		<p>
		It seems to me that a historical threshold which might be inevitable, or even overdue, has been crossed by Elon. This is: the final closure of Enlightenment public reason. The internet, rather than representing a pure public square, seems to be destined to culminate in the destruction of said concept through the overproduction of communication. With the birth of cancel culture — this culture of bad faith in which people would seek to tear down their rivals by publicly misinterpreting their words and maligning their intentions — communicating one’s thoughts publicly quickly became unsafe. It is far more productive, perhaps, to seek truth only among friends, in back channels, than submit one’s opinion to the judgment of the panopticon. And of course, holding private conversations with people all over the world is trivial — it takes only a few seconds to make a new group chat.
		</p>
		<p>
		Thus, the horizon towards which this trends is a closure of public discourse, and one in which discourse can only happen in closed groups, such as corporate firms, group chats, secret societies. A world in which sovereignty moves from the public lectern to the inner sanctum of the temple — a world of silent conspiracies. In a sense, this is the truth of the world we always have lived in, its Real — and yet the fiction of the public square held a reality of its own, like the fiction of a virile war god which can nevertheless march people into battle. In its absence, the new grand stage of the social becomes one in which people speak not to each other but for reasons related to advertising — to lure, to grab attention, to tease, to intimidate, to terrorize. A social order of clown masks and clutched knives.
		</p>
		<p>
		The clown play, the reddito-fascism, we have the example of what this looks like: e/acc. (<a href="https://www.motherjones.com/politics/2023/12/effective-accelerationism/">If you don’t know what this is then you can read this Mother Jones article in which I am quoted.</a>) E/acc is a movement which begins with bad faith: it exists to troll effective altruists, who, let’s remember, for all their flaws are a movement oriented around discovering better strategies for charitable giving. Actually, the e/acc poster says, trying to do good in the world, organize people, whatever, is a waste of time, because the capital markets are already maximally oriented towards goodness. So you should do what the e/acc poster does, which is go to work, and then spend your leisure time trolling the do-gooders on the internet who are trying to coordinate around higher pursuits. “Anonymous shitposting” on X, this supposedly subversive thing to speak truth to power, is now weaponized around telling people to go to work and focus on productivity quotas.
		</p>
		<p>
		Is this not precisely what we expect from the new order of the depleted public square, and the specter of tech corporations subsuming the role of the state? E/acc holds: to talk publicly is to be useless — what is good and useful is to keep your sincere efforts within your corporation, and then spread dissimulation to salt the earth outside of it while simultaneously advertising a kind of personal brand. Any kind of great American reaction is not going to proceed by naked censorship and ideological imposition — the most important possible thing to control an American is to tell him he is beautiful and noble for speaking his mind openly, like that Norman Rockwell painting everyone posts as a meme. Under wokeness, there has been so much critical discourse about race, capitalism, etc., albeit largely from a vocal minority in the creative-production class. How can the reaction unfold unless it utterly silences these people — it cannot be so crude as to throw them in jail; it must simply drown them out. There has to be this unleashing, this swarming of vulgarity and confusion — can the reaction win without it?
		</p>
		<p>
		The fear is that what is lost is the human being in any kind of its ability to develop beyond meat shuffled through various technological systems — the office, the subway ride home, the advertising matrix of streaming content. Is this possible without culture? Is culture possible under conditions like this? It’s not like there’s another site of production and dissemination for it to move to; there’s only one Twitter.
		</p>
		<p>
		Nick Land at this point must certainly have earned the title of the most important philosopher of the past half-century. Everyone now is thinking in relation to accelerationism. In the context of the growth of acceleration, neoreaction, the dissident right, is Elon like the Stalin to Nick Land’s Marx? Elon of course almost certainly does not know who Land is. But they share the same triad of objects of zeal — a sense that the industrial process must intensify in an uninterrupted way, racism, and a joy in spreading irreverence as far as possible. Racism, this all-too-human passion as old as man, becomes the weapon to dismantle the human plane, by accelerating its internal differences until it breaks. The emergence of this pure demonic theater of simulacra where the formality of a public sphere once lingered is its shattering into entropic fragments as it splits apart, a spiral into radio static and catatonic schizophrenia.
		</p>
		<div><a href="/">← Home</a></div>
    </div>
		
  )
}

export const Head: HeadFC = () => <title>Just to state the obvious, Elon’s takeover of Twitter is a major historical event</title>

export default CSVSPage

