import * as React from "react"
import type { HeadFC, PageProps } from "gatsby"
import "../index.scss"

const CSVSPage: React.FC<PageProps> = () => {
  return (
    <div className="container">
    <h1>Network Solipsism</h1>
		<div><a href="/">← Home</a></div>
		<p>
		<i>This piece was written as a submission for the forthcoming essay collection <a href="https://shop.becoming.press/products/dialogues-on-corecore-the-contemporary-online-avant-garde-onty-smith-eds-et-al-2024">“Dialogues on CoreCore & the Contemporary Online Avant-Garde”</a> to be published by Becoming Press — a project I endeavored to support with a contribution to due to a friend’s involvement. However, the primary editor, a man who calls himself <a href="https://www.instagram.com/the.ontological.turnt/">“The Ontological Turnt”</a>, would not publish this piece without demanding significant cuts – asking to excise nearly the entirety of the piece leaving only the very beginning and end which are specifically about the “CoreCore” TikTok trend: an utterly nonsensical and disrespectful suggestion, as these leftover fragments would not resemble a coherent essay. Therefore I am instead publishing it here.</i>
		</p>
		<p>
		<i>I want to know — what’s up with this plague of derivative motherfuckers, all seemingly in grad school or adjunct hell, who name their internet account some portmanteau of a philosophical reference and some Gen Z slang, ideally sexual, so you know that they like, read books but also party? WOW that’s crazy, I’ve like, never met a person like that before!! You’re telling me books could be cool? These copy-and-paste mfs all call themselves shit like “fredrick slaymeson” “martin hoedigger”, “diasexual materialist” etc. I just saw today a new account on my timeline today “francis fuckyomama” which is admittedly a pretty funny name. But is someone going to tell these people this trend is played out? </i>
		</p>
		<p>
		<i>So this guy, “The Ontological Turnt” is telling me “I don’t understand why there is a section in this piece about you wanting to fuck some random girl in a kava bar, that has nothing to do with CoreCore, why is it in there?” Uh because it’s hard, it gets the people going. You’d think the Ontological TURNT would be able to conceptualize that, but apparently not. Talking about wanting to have sex with strangers in a bar is 100000000 times more interesting to pretty much any reader than the “CoreCore” TikTok hashtag, which I don’t know why he felt the need to commission an entire book about, but that’s his business. Anyway.</i>
		</p>
		<hr/>
		<h3>Bloom on his phone</h3>
		<p>
		The central feature of our world today is that we are all always on our phones. What is the fundamental essence of these devices? It is that we are now – to an approximation – <i>always open to communication with every other person in the world at all times</i>. Yet we are lonelier than ever. You do not feel more connected your fellow man amongst all the chatter which piles up in your notification feed every day. You do not feel a relief that an infinite set of possibilities for human interaction is only a button press away. You feel ever more like a stranger in an impossibly vast crowd.
		</p>
		<p>
		You return over and over to the timeline, to the For You page, because you are lonely inside your bedroom, and here in your hands is the portal to human connectedness — it does not seem to exist down the street, at a bar, in a park, or what have you — because out there, they too are on their phones, seeking connection or stimulus through the screen and not the world around them. It is widely felt now, for example, that with the widespread use of dating apps for romance, the possibility of meeting an attractive stranger at a bar, sharing a few hours of drinks and conversations, and then making love with them is mostly closed, at least to those not among the most daring of us. Those who seek today’s form of promiscuity are on their phones.
		</p>
		<p>
		For people addicted to the internet, the advice is “go outsideˮ. But there is no outside. Rather, the digital plenum behind the glass of your phone screen is now the great outside, with its infinity of possible connections laid before you, as well as its array of new depraved and divine spectacles always available to gawk at. This is why you are addicted to it, seeking amongst the constant novelty the sudden opportunity for connection with some person, product, brand, piece of knowledge which could change your life.
		</p>
		<p>
		At the <a href="https://www.instagram.com/p/CzNOPBntUGA/">CoreCore Symposium</a> held in Manhattan at the School of Visual Arts, <a href="https://www.instagram.com/heaveninterface_/">Dylan Smith</a> suggested that CoreCore was notable because it is the first art form <i>by and for Blooms</i>. “Bloomˮ refers to Tiqqunʼs <i>Theory of Bloom</i> text, the title of which in turn refers to the character Leopold Bloom from James Joyceʼs <i>Ulysses</i>. Bloom, an awkward introvert, as well as a Jew confronted with the worldʼs prejudice, is cut off from the society around him and exists in a tortured maze of internal reference points within his head. Today, we are all like Bloom, which is to say we are all irreversibly severed from each other, and from our outsides. But Tiqqunʼs book contains a note of hope. As the condition of introversion and abandonment spreads to everyone, as we utterly lose the world, we also begin to lose our chains. Like Marxʼs proletariat, which finds the will to overturn its master only when it has been globally reduced to the same flattened immiserated state: at the maximal point of our retreat inward, we may suddenly rediscover the outside again, in the form of new social relations.
		</p>
		<p>
		The panelists at the symposium generally agreed that the fundamental function of CoreCore was to break the passive viewer out of the logic of the timeline, that is, of the For You page. CoreCore is a protest against the logic of the overproduction of “cores", eg cottagecore or dark academia. A “coreˮ in this case is a sort of individualized fantasy life to yearn for, which can then be marshaled into a set of aesthetic principles to decorate your existing life and provide as a template for fashion and interior design. Fantasy, followed by consumption.
		</p>
		<p>
		By contrast, CoreCore presents the viewer with the radical opposite of “core”: a stark naked look at the devastation of the globe through the industrial production which fuels the Western consumer. Here the viewer is confronted with “the production of the productionˮ of their fantasy — the machinery behind the curtain — thus collapsing the fantasy and revealing the brutality of the world for what it is. CoreCore "breaks the logic of the For You pageˮ by forcing the viewer to suddenly stop their hypnotized daydream and confront the reality behind their scrolling experience.
		</p>
		<p>
		In this moment, the consumer has not only deserted the world, but has gone a step forward to desert the fantasy that carries out its devastation and abandonment. Left with nothing but a skeletal corpse, are there new possibilities in this vacuum?
		</p>
		<p>
		After the CoreCore symposium, I decided to re-read <i>Theory of Bloom</i> myself, and went to a local kava bar to do so. I frequent this kava bar in part because it is one of the few places in New York City where it feels like there is kind of an organic community that hangs out there, in which one could strike up a conversation with a stranger. However, I almost never do. It feels like the people there are in a slightly divergent subculture of vaguely artistic gentrifiers from the one my friends and I seem to occupy (the people here act kind of in the vein of Burning Man people, but more queer-coded), and this is enough to put a barrier between me and them. Thus, I sit alone on my laptop amongst lively chatter which I mostly choose to not engage in, and contribute to the decline of the very conditions which led me there in the first place. Though most bars in New York advertise around the fantasy of community, but only in fact cater to isolated groups of people who arrive together, this bar manages to bring forth the actual thing. But I apparently, as evidenced by my actions, am only here for the fantasy.
		</p>
		<p>
		As I am reading <i>Theory of Bloom</i>, I become uncomfortably aware of this irony, especially because there is an alarmingly beautiful woman sitting perpendicular to me. She is reading some kind of book herself. It occurs to me that everything is in place to actually connect with a stranger in the way I often vaguely intend to when coming here, and I, in a sense, am left with ˮno choiceˮ. I ask her what she is reading. I am a little surprised by the way that she responds to my question with not mere politeness, but sudden enthusiasm, leaning towards me with a wide-eyed stare as she explains. She doesnʼt know what sheʼs reading, she picked it off the shelf over there – itʼs some kind of new age book on how to determine what type of ascended being you can most easily connect to. She is also holding a set of tarot cards, which she also found over there, and doesnʼt know what they mean or how they work either.
		</p>
		<p>
		She is new to New York City, she is staying with a friend temporarily for a few more weeks and does not know where she will be staying after. She has been wandering around all day in Bushwick, going in to random shops and looking at random things, saturated with awe of the city. She is not a Bloom. She has little to remark on what she thinks of her wanderings, but seems eager for connection; with everything she says she stares at my expectantly, leaning in, waiting for my reaction.
		</p>
		<p>
		She is extremely pretty. Sheʼs probably several years younger than than me, but on top of that possesses a viscerally naive quality that makes the thought of flirting with her, (or maybe even talking to her?) feel unsettlingly predatory. There is a distant la-la quality to her which feels almost schizoid; maybe she was raised in a cult. I donʼt really know how to respond to what sheʼs telling me. Am I curious to hear more about her life? Not really, in my heart of hearts.
		</p>
		<p>
		I canʼt tell if I want to talk to her or not. I read a page or two of the book, then, suddenly feeling again exposed by the textʼs critique of isolation, I think of some question to ask her again. Apparently, as a Bloom, I am too neurotic to dissolve the dilemma one way or another. Were I some tribal man, rather than a modern one overburdened with self-consciousness and de-libidinalized by overstimulation, perhaps my desires would be simple and straightforward, perhaps it would never have occurred to me to have any other goal in mind other than getting to a place where I can tear off her clothes and make love. But the other alternative – to just admit to myself that my true desire is not to boldly break out of my self-imposed subjective prison and discover the other human being before me – but rather to read my book in isolation, to eventually write my stupid cynical essay, continue to despair over a shrinking horizon of meaning, and move on to the next one, convinced I am engaged in an important creative ascent – is also too difficult to simply affirm as my own true choice, and so I am stuck agonizing and prevaricating, too distracted by the stupid irony of the situation to even focus on reading.
		</p>
		<p>
		In the end, of course, the inertia of isolation won the day.
		</p>
		<h3>Love did not win</h3>
		<p>
		The question that the CoreCore panelists turned to was: okay, so CoreCore has managed to disrupt the logic of the timeline, has managed to disrupt the hypnotic loop of consumerist fantasy which the viewer expects with a view of the visceral real behind its production — but then what?
		</p>
		<p>
		Is it possible for CoreCore to move into a kind of call to action? Mason Noel, the originator of CoreCore, had previously made videos in the genre with instructions on how to bomb power stations, blurring the lines between “artˮ and incitement to violence.
		</p>
		<p>
		<a href="https://www.instagram.com/lifedrive____/">Alice Aster</a>, when this point was brought up at the panel, spoke up and told the crowd that she knows a lot of people who went down this road, and, trust her, you donʼt want to become a terrorist just because youʼre fed up with capitalism. You donʼt actually want to spend decades in prison just to blow up a generator that theyʼll replace three days later anyway. Whatʼs more, she continued, you donʼt want to join a commune either — theyʼre all gross polycules, and being in a gross polycule is not going to improve your life. Focus on more immediate practical solutions like mutual aid, she says, rather than overturning the system all at once.
		</p>
		<p>
		Eddie Hewer, in turn, then pointed out that since we have been talking about Tiqqunʼs <i>Theory of Bloom</i> so much, we should keep in mind that Tiqqunʼs solution actually <i>was</i> to blow up critical industrial infrastructure. Not only that, but they also formed a commune — nine of them apparently did manage to exit the heart of capitalist French society in Paris together and moved to a rural area where they ran a small farm and a store. If Tiqqun was secretly a “gross polyculeˮ at heart, we have no evidence of it, but it does seem like their terrorism was mixed in with an erotic thrill, a fact a reader of their texts will find unsurprising.
		</p>
		<p>
		One can only imagine the heights of excitement which Julien Coupet, Tiqqunʼs alleged leader, and Yildune Lévy experienced together on November 7, 2008 as they went on a low-speed chase with police cars, only to return to the scene of a crime from the previous night and make love in their parked car next to train cables they had sabotaged the night before — this is by their own admission to the judge. The thought of the doomed romanticism of the empty gesture of destruction, the flight from the law, combined with the thrill of orgasm — how it must have been savored by these young poets and philosophers. Is this the height of it; the truth of the communal experience outside of alienation which Tiqqun pushes us to seek?
		</p>
		<p>
		I recently watched an HBO miniseries on a cult called “<a href="https://www.rollingstone.com/culture/culture-features/love-has-won-amy-carlson-mother-god-1254916/">Love Has Won</a>ˮ, a cult which was perhaps notable because it recruited its members almost entirely over the internet. Various journalists have reported on the group with introductions in the vein of “Is this a cult? Many accuse the group of being one, but its members insist society itself is the real cultˮ. But Love Has Won is the type of group where if it is <i>not</i> a cult, itʼs unclear what else would be. It is about as <i>classical</i> of a cult as one can imagine.
		</p>
		<p>
		A bunch of people (about twenty at its peak) all decided to live in a house together and worship one woman, Amy Carlson (who is now unfortunately dead, killed by alcoholism and an unwise alternate health regimen) as God, believing her to be the resurrection of Jesus Christ. It almost feels charmingly quaint, a throwback to a more innocent time perhaps, that members recruited from the internet could be recruited into something so straightforwardly culty rather than layered with Gen Z irony and self-consciousness. Nor was there any complex funnel of delicate grooming before its members were invited to worship a random woman as God; this was the pitch right up front.
		</p>
		<p>
		Not only that, but Amy Carlson seems to eschew any real attempt to <i>act like</i> God — there is no unblinking stare, soothing voice, slow and delicate movements; the standard calling-cards of a guru. She is on camera drinking heavily, swearing, dancing to pop music, barking at her acolytes. Perhaps there is something paradoxically charming about this — imagine if God came to earth and she was revealed to be a kind of Taylor Swift wine aunt; perhaps there is comfort in this familiar image. As for her followers, they are hardly a band of social rejects; many are very attractive, many are leaving jobs and relationships and coming with significant amounts of money to give to the cult, nor do they show signs of being unstable or mentally deficient.
		</p>
		<p>
		What kind of world is this that these people can be recruited from to join what seems like the least convincing religious group possible? In the documentary, we see Amy Carlsonʼs experience as she goes from regular American to cult leader through a tumble down the new age internet rabbit hole. We see these new age websites — they are full of bright glowing portraits of ascended Theosophical masters with wide open eyes throwing up mudras, and underneath them are all kinds of positive affirmations — “you are a bright and shining starˮ, “you are more powerful than you could possibly knowˮ. After some time making friends in these circles, Amy began talking to a man who went by a name of WhiteEagle who told her that she was God: specifically that he was “Father Godˮ, and she was destined to be his “Mother Godˮ to complement him. In December 2007, Amy decided to answer this call to become God and move across the country to be with WhiteEagle, leaving behind a job as a manager at McDonalds, a husband, and three kids.
		</p>
		<p>
		The documentary has some genuinely sweet footage of Amy and WhiteEagle road tripping across the country together, seemingly having returned to a state of childlike wonder, in awe of their mutual discovery that she is God, he is God, and they are God together, having created the world, and then having somehow lost themselves in it, are amazed to discover that they have now found each other once more.
		</p>
		<p>
		But it was not to last. After seven years together, Amy and WhiteEagle eventually split up, but she still remained faithful to her identity as Mother God. This is when she began looking for new followers.
		</p>
		<p>
		The beliefs of the Love Has Won members are as numerous as they are curiously dadaist. Not only is Amy the resurrection of Jesus Christ, as well as hundreds of other figures like Harriet Tubman, Cleopatra, and Joan of Arc, but the members consider Donald Trump to be her father and Elvis Presley to be her son. She regularly communicates with a team of spiritual advisors which she calls “The Galacticsˮ who fly around in a spacecraft above Earth; foremost of among them is the deceased spirit of Robin Williams.
		</p>
		<p>
		Again, these people do not seem mentally feeble or prenaturally insane. What seems to have happened is that they have, one step at a time, entered into a kind of <i>purely affirmationist epistemological register</i>. A statement can be made, such as “The Galactics have reported that Amy Carlson will one day be President of the United States of Americaˮ, and the members will test for its truth by closing their eyes, <i>feeling</i> it out in their bones, and announcing something like: “somehow I just <i>know</i> it is trueˮ. If it feels right, it is right. This is the logic that is in the name “love has wonˮ — really their insistence that this kooky lady is God and their mother is not much more than an elaborate way of saying that they love her, it seems, and love each other as a kind of adoptive family, in a way that can be a deep commitment to somehow transcend all the horrific logic of this world.
		</p>
		<p>
		There is a way in which Love Has Won can be read as a kind of reaction against and resistance to our contemporary world of capitalist production. In the cultʼs parlance, this was the “3Dˮ world of alienated labor, isolation, stress, paranoia, routine, and empty consumerism, which one could escape from by entering the 5D realm of pure love, openness, and affirmation around Amy. The fact that Amy had managed a McDonalds, such a symbol of consumerist disease, conveniently mythologized her to the cult as an Orphic figure who, forgetting she was God, had descended to the absolute kernel of the 3D realm, only to make the most miraculous escape through self-understanding. Many of the members had justified trauma with the horrors of the arbitrary unfairness of modern capitalism — one woman joined after coming out of a coma to learn that she was now half a million dollars in medical debt, and feeling all hope for happiness escape her.
		</p>
		<p>
		We can see, therefore, how powerful this form of internet content can be — the internet content which Love Has Won disseminated on live stream every day to find members. It does not need to be convincing in any shape or form to compel people to radically uproot their lives and make dubious commitments to a strange woman. All is needed are the basic steps of providing a mirror for peopleʼs alienation, giving them a narrative which feels right to repeatedly affirm, and telling them that outside the abyss of isolation from their fellow humans they experience is a new world of love they can step into, like putting on a new warm coat.
		</p>
		<p>
		One feels while watching Amy that the label of “cult leaderˮ belies a certain innocence which she seems to hold throughout the whole process. She is not carrying out some ingenious psychological plot to manipulate her followers, rather, through these new age websites, she herself has fallen victim herself to this leaderless spiritual process of exiting the world into the delirious 5D realm of constant love and affirmation.
		</p>
		<p>
		Some of what is endorsed in this interlinked web of affirmation is disturbing — the cult once claimed that Adolf Hitler was one of the galactic light workers, and that the Jews he killed had it coming because they didnʼt listen to him. This moment of fascist rhetoric is a particularly bold eruption of a larger narrative the cult has of “the cabalˮ — a demonic group keeping the world in a 3D low-vibrational state, whom all negative events the cult experienced could be blamed on. This and other beliefs have indicated a link between Love Has Won and the Qanon movement.
		</p>
		<p>
		And yet, there is still a sense in which the attitude is more small-c communist than it is ultimately fascist — the group wants to live in a small sustainable collective experiencing communal love; they do not have fantasies of sculpted Aryan bodies, war, dominance. But somehow, in all this, these surreal internet milieus in which it is possible to harvest lost souls, the streams are radically crossed. Why is this? Will it always be this way? And could it somehow be otherwise?
		</p>
		<h3>Network stupidity</h3>
		<p>
		These are the questions that any kind of radical online art which provokes a positive call to action will have to address. Can people be propelled by content surfacing up through the digital to do something productive and transformative? Or is there something intrinsic to the digital which pushes against this? Or in other words, again, is there a way which CoreCore could, after breaking the logic of the timeline and forcing the viewer to confront the real, inject back into the logic of the timeline a desire to truly change oneʼs habits? Or would this just be another malignant fantasy?
		</p>
		<p>
		Dylan Smith, during the CoreCore panel, suggested that CoreCore was moving to a kind of <i>divine surrealism</i>. This conjures a similar idea to the name of Tiqqun — referring to the concept of <i>tikkun olum</i> from kabbalah, or the repair of the world; the return of the fragmented sparks of divine light to their source in the godhead. Fragmented, lonely subjects, torn apart by the viciousness of capitalist society, can perhaps return to some kind of primordial unity in divine love.
		</p>
		<p>
		But is a call towards divine unity enough? The medium is the message. The irony of spreading such a message on the internet is that there is a sense in which the call to divine unity <i>already</i> immediately reflects the experience of going on the internet. Behind the screen of the phone is an unthinkably complex web of social relations reified in a single unity of the glowing altar of the feed, through which it is possible to imagine a global connection with all of humanity. There is a divine surrealism of the riot, and there is a divine surrealism of the social graph, and the question is how to understand their relation, or make sense of the interpenetration of one within the other.
		</p>
		<p>
		This is the question addressed by a small online movement around the concept of “network spiritualityˮ, consisting of what could be described as “internet cultsˮ  <a href="https://miladymaker.net/">Milady Maker</a>, <a href="https://cashedcobrazhousewriter.substack.com/">Angelicism</a>, and <a href="https://knowyourmeme.com/memes/sites/based-retard-gang">Based Retard Gang</a> being the prominent examples, which have prominently risen and fallen in net-art and associated subcultures in New York City. In a sense, these are like the affirmationism of Love Has Won, transcoded for the hyper-referentiality, ironicism, and easy distractibility of Gen Z. One example of this affirmationist language, excerpted from the Angelicism blog, reads: <i>“We are living in a new world of endless possibilities and newly tractable calculations of finitude. There is still room for all this weird new art and the internet will be the best means to spread it. STAY INFINITE. JUST FALL UP BRO. Angelicism is a great word to have since l created my clones I will live forever in the womb I will be forever a part of a future that may be yours I will live forever I will breathe in my heart of infinite love forever I will wonder at the opposite of opposites I will breathe in my heart of infinite love forever.ˮ</i> The reader is invited to transfer their experience navigating a bewildering register of intermixed semiotics experienced as “internet artˮ into a fantasy of infinite love through endless production, if only one leans into it — <i>“Angelicism is falling up and falling up is like prayingˮ.</i>
		</p>
		<p>
		In a way — is the affirmationist register of Love Has Won not a kind of revealed truth of discourse production on the internet? One spreads a message by a pure “yesˮ — the like, the retweet — in a way that is not possible in a pre-internet age. Is the internet — a set of cables owned by a duopoly, datacenters owned by military contractors, profiting over surveilling you and selling your data — part of the “3Dˮ world? Or from the userʼs perspective, perhaps it really is this new “5Dˮ world of love and light, since anyone says that enough people affirm takes on a reality; might as well be considered real and true.
		</p>
		<p>
		People confronted with these internet cults often do not know what to make of them — are they somehow dangerous, do they abuse people? What makes it even more confusing is that the members of these groups sometimes falsely spread rumors that they are and they <i>do</i>, so as to give themselves some kind of aura, or simply drive attention. But unlike a group like Tiqqun or Love Has Won, these groups do not seem to recruit people to live together in some house, or dedicate large portions of their lives to the group. Rather, they primarily seek to leverage people into spending a lot of time amplifying their message across social media. In a sense, they are like elaborate versions of the “email chainsˮ of the early internet — self-replicating bundles of information which simply seek to encourage users to spread them as far as possible — only now sending one email is not enough to satisfy the virus; one must be consistently rallied to spend time in Discords, group chats, editing memes, writing Substacks.
		</p>
		<p>
		The difference between the idiocy and delusion of something like Love Has Won and the relative sophistication of something like Angelicism which allows it to enter the subjective register of “artˮ is that the latter has a self-conscious reflexivity in its construction. It draws on accelerationist philosophy to theorize about the conditions which allow internet images to draw people out of their day- to-day existence into a compulsion to spend hours a day spreading a memetic gospel. The theory and the practice fold onto a flat plane — the theory itself becomes embedded in data-objects engineered to go viral, in actions such as superimposing passages from accelerationist Substacks upon hypnotic loops of skinny women dancing, which then in turn are uploaded to TikTok.
		</p>
		<p>
		The danger we have arrived at is that the obverse side of CoreCore could look exactly like this. Given an interpretation in which CoreCore is the ugly “realˮ of the timeline, having previously been occluded by a consumerist fantasy — would the next step, after identifying the need to spread a positive desire, not be to explore the “realˮ of the production of the fantasy, in this very direct way? A kind of Bauhaus of the timeline, in which form follows function. <i>Whatever impregnates the userʼs imagination and spreads across the network must be true</i>, is the potentially dangerous accelerationist thesis someone adventuring down this path might discover.
		</p>
		<p>
		Conveniently, the accelerationist thesis which valorizes spreading a body of informational material as far across the network as it can go plays into an economic reality in which ability to spread information is directly linked to the accumulation of capital. Nebulous abstractions like the “attention economyˮ are no longer even necessary — we now have cryptocurrencies and NFTs to directly transform a viral trend into net worth (all three “internet cultsˮ referenced above used NFTs to take profit). “Itʼs like memes are actually capital now,ˮ a CEO like Elon Musk presumably thinks to himself as he hovers over the shoulder of one of his overworked engineers, watching him change the Twitter bird logo to the face of the Dogecoin mascot.
		</p>
		<p>
		But these minor, theory-informed internet cults which appeal to net-artists and nerds are small game compare to the ones which ensnare millions. By far the savviest, most infamous hawker of these methods is Andrew Tate, whose “cultˮ of misogyny, hustling, and self-improvement was deemed so disturbing to the existing order that some schools in London developed a program to “deradicalizeˮ middle schoolers away from it. Tate, like Love Has Won, urges his followers to step out of the “matrixˮ — which is the unity of all the information they have been told, fantasies that they have been sold, all deliberately engineered by shadowy figures to control them. At times, this critique can even present itself as revolutionary — there is a moment where Tate tells his followers that capitalism <i>inherently</i> relies on an underclass of people reduced to a level of slavery, and you yourself have been conditioned to be one of these slaves. The way out, of course, is to enter his meme factory and join his rising tide. The close at the end of the sales pitch is your joining a class on how to make money through selling similar content as Tate, which also requires its members to spread Tateʼs content on social media as a condition of participation.
		</p>
		<p>
		In a way, the Andrew Tate fantasy is the inverse of the consumerist fantasy. It is a <i>producerist</i> fantasy; which is to say that Andrew Tate spares no words in telling you that capitalism is manipulation, the media is manipulation, politics are manipulation, but proposes to spread the means of production of manipulation as widely as possible so that his followers can get rich too. And in a sense, with people becoming rich overnight with cryptocurrencies, simple tech apps, viral products, do we not already have all we need in the palm of our hands?
		</p>
		<p>
		The “attention economyˮ method is what Love Has Won in fact used. Their small commune-of-sorts had no actual machinery of material production available, so, dropping out of society, all they could use was their laptops to figure out how to make money somewhere. The cult members spent all day streaming for a small audience which believed in the “5Dˮ gospel and would donate money to keep the cult members housed and alive. Love Has Woman also had a small store to sell supposedly-healing merchandise; the same lucrative method of monetization of Alex Jonesʼ InfoWars.
		</p>
		<p>
		Walter Benjamin said that fascism was the subordination of politics to aesthetics, and that to counter that, the revolutionary movement needs to subordinate their art to the political. Somewhere in this is the promise of a holy grail of a conceptual object in which the political and the artistic are entirely one — an object in which its potential to transform social relations is the source of the beauty and the poetry. We seek something like this in these new avant-garde forms of digital content. But are these new forms of social relations just out of reach and to be discovered through the digital perhaps even more exploitative, more perverse, more ultimately alienating?
		</p>
		<p>
		All this is to say, that there are a lot of potential dangers and pitfalls in the road of engineering viral TikTok content to attempt to break people out of their existing prisons. It may be that merely by provoking in-person moments such as the CoreCore symposium and books like this, CoreCore has already done its job in inspiring a positive direction. Or there may be more work for CoreCore — or a movement inspired by it — to do on the digital front. But the perils are many, and love, openness, light, may not be enough. 
		</p>
		<div><a href="/">← Home</a></div>
    </div>
		
  )
}

export const Head: HeadFC = () => <title>Network Solipsism</title>

export default CSVSPage

