import * as React from "react"
import type { HeadFC, PageProps } from "gatsby"
import "./index.scss"
import compass from "../images/corporate-realism-compass.jpg"

const CSVSPage: React.FC<PageProps> = () => {
  return (
    <div className="container">
    <h1>The Corporate Surrealist Vibe Shift</h1>
		<p>Okay, so everyone wants to know what Corporate Surrealism is. But first of all, we’re not sure if defining things is actually something we want to do. Once you’re defined, that’s the first stage in the process of getting captured, becoming real. The most successful vibe shifts seem to also totally lack definitions — take “wokeness” for example. Keep it open-ended, keep it loose, keep it extensible. Make it only a signpost, an indicator of a territory. And then put materials in that territory that people can run away with.</p>

		<p>Even if we more ground it more theoretically — which is the plan eventually — Corporate Surrealism has to first and foremost be a vibe, and remain one. Even if the goal is also discover a solution to our conceptual, political, and spiritual problems. It begins and ends in a vibe.</p>

		<p>Corporate Surrealism is a good designator of a vibe shift because you already know what it means when you read it, right? Basically we are bringing a surrealist attitude and vibe to corporate settings and structures. Fundamentally this is about expression. We need to at some point historicize this in the context of the surrealist art movement and its origin point, but let’s say for now — to be surreal is to be strange, aloof, provocative, violent, erotic, devoted, in love, erratic, implacable, not-of-this-world… if you want to be, that is.</p>

		<img src={compass}/>

		<p>We can contrast this with a few other territories. Corporate Realism: this is LinkedIn, the name and the face and the resume, the handshake, mandatory diversity training, “let’s circle back”. It’s the contractual obligation to negate all expression which for some reason is necessary to enter the corporate environment, in the typical case.</p>

		<p>There’s also Corporate Anti-Realism. One thing that is important to understand about the Surrealist imperative is that, if anything, it’s more of a reaction to Anti-Realism than it is a reaction to Realism. Surrealism rejects Realism, but is not <i>against</i> it; this is crucially important. Corporate Anti-Realism is kind of like Bitcoin maximalism or Urbit, or other types of fantasies in the direction of anarcho-capitalism. Curtis Yarvin’s “formalism” is peak Anti-Realism. Reactionary anarcho-capitalism is cope because it’s imagining that you could somehow hold in place the corporate structure but reject its aesthetic and spiritual form of expression; without fundamentally changing things.</p>

		<p>And then finally there’s Corporate Quasi-Realism. To me Corporate Quasi-Realism is exemplified by the twitter user Visakan Veerasamy <a href="https://twitter.com/visakanv">@visakanv</a>. His thing is posting in a way that’s “kind of like LinkedIn, but also kind of not”. And the “kind of not” is filled in by being more sincerity-coded, going for this angle of deep introspection and exploration of the self. The promise seems to be that by doing this, you will also get better at monetizable skills, such as marketing, copywriting, project management, etc.</p>

		<p>I went to this conference hosted by InterIntellect at which Veerasamy was the featured speaker. The conference cost hundreds of dollars to attend but a friend got me in for free. It was kind of uncanny because it was billed as a “writers’ symposium” and I was invited because I was a “writer” but it became clear when I was there that the writing everyone was doing was some sort of Substack hustle because they wanted to build a sales funnel for a business, or for some kind of influencer brand to monetize. However, no one was willing to state this explicitly: it was all this self-congratulatory stuff about “we have so many intellectuals in the room here!” and “being an artist is about self-expression” and whatnot.</p> 

		<p>Of course, at the time, I was also engaged in the same process: my primary writing project was the Harmless AI Substack the goal of which was to elevate Harmless AI as a vehicle which would eventually accumulate capital. But I felt as if there was something fundamentally different about the Corporate Surrealist activity I was engaged in and the Corporate Quasi-Realist activity the people around me were doing. Corporate Quasi-Realism is kind of like this weird cope that you can have your cake and eat it too without serious struggle: that developing one’s self expression naturally coincides with making easy profit in a corporate context, rather than often unfortunately manifesting the reverse (the hiring manager is nervously looking at your tattoos).</p>

		<p>Corporate Surrealism is a descriptive indicator of certain trends in the world, but is also a positive prescription. The Corporate Surrealist Vibe Shift is already undergoing, and has been happening, but our mission is to consolidate and intensify it with increased clarity. We did not name the term Corporate Surrealism. We thought we had gotten it from Grimes (who we stan), but it seems like Grimes might have gotten it from her ex-husband. You could say that what has been going on at Twitter since the takeover has perhaps been an example of Corporate Surrealism, but in a sort of negative sense that shouldn’t be presented as a model to emulate.</p>

		<p>There is a sense in which Corporate Surrealism is manifesting itself on the macro level, but what we were more interested in is noticing the trend immediate to us of people developing what we might call “surreal corporations”, such as Grift Shop, Remilia Collective, Seed Oil Capital, 21e8, Praxis Society, to loosely name a cluster. What these corporate vehicles have in common is that the value-generating prospect is inseparable from a sort of public-facing performativity, even of an avant-garde variety that is bewildering to most people. And this performativity is inseparable from an creative expression that comes not immediately from any profit motive, but through an expression of the creative will, in the fashion of an artist.</p>

		<p>We were saying on Twitter that Corporate Surrealism is “the only viable alternative to twentieth century liberalism”, but it isn’t actually some kind of political ideology for the masses. It’s more of a “ride the tiger” type thing. The goal of theorizing Corporate Surrealism would be to establish blueprints for establishing “surreal corporations”, which would be a praxis in which people are able to craft corporate structures which are able to acquire and accumulate capital, but also serve as a vessel for collective expressions. Corporate Surrealism is interested in learning from faith-based business practices, eg evangelical Christian corporations, Orthodox Jewish corporations, or Sharia Muslim corporations, because we are interested in learning how extreme spiritual devotion is compatible with earning a lot of money. It’s not like Corporate Surrealism has nothing in common with utopia-minded anti-corporate endeavors like anarchist co-operatives, but there is kind of a skill issue at play: a lot of times these organizations are simply dysfunctional or unable to live up to their ideals. Also with leftist groups you have this problem where there’s a lot of slave-morality and you end up with a bunch of losers dragging each other down together instead of collectively building each other up.</p>

		<p>When it comes to “left” and “right” and so on, Corporate Surrealism isn’t really that interested in these outmoded 20th century categories. The Corporate Surrealist Vibe Shift is more like the CIA, where it’s content to play all sides and situations and steer them for its own purposes. But there is also an ethical aspect to Corporate Surrealism: one positive aspect that self-conscious Corporate Surrealism has over the status quo is that it invites an attitude beyond what is becoming typical in some of these profit-seeking spheres such as cryptocurrency sectors, in which a sinister self-seeking attitude can take hold that goes something like “I will sacrifice all of my life and kill whoever I need to to secure money in my bank account for my children”. The capitalist corporation itself is by its nature a conspiracy to collude with a group of actors in order to exploit those outside of the corporation for the benefit of those within it. However, the surreal corporation has a slightly different attitude towards the world outside itself, via its attitude regarding expression — because artistic expression is in its essence a universally handed-over gift.</p>

		<p>Corporate Surrealism definitely has a particular relationship with cryptocurrency and the culture around NFTs. What we are seeing with some of these NFT projects, in particularly being inspired by our close proximity to the Milady subculture, is that an abstract sort of vibe can be directly transmuted into capital, through an almost literal sort of alchemy — the transformation of base matter into gold. New precious metals emerge as a directly psychic and artistic phenomena as people collude around symbols which resonate to them and decide what they want to inflate. For Twitter management to change the Twitter logo to the “Doge” icon is a very Corporate Surrealist action as it reveals what Twitter has been transformed into — a company no longer running off of practical decisions for developing software infrastructure, but for the sake of the personal expressions of the man who runs it, as well as those who share his taste in politics and humor, as they can all elevate the symbolic and actual value of the “Dogecoin” conceptual currency together in sync with Twitter management decisions, a sort of decentralized conspiracy which uses art and humor to keep its participants in sync, rather than explicit organization. In a sense, to turn the Twitter logo into the Doge is a gift from the Twitter corporation to the world: but specificly those in the world who were “already on the same frequency” and had purchased Dogecoin for one reason or another.</p>

		<p>The slogan of Corporate Surrealism is a lyric from Kanye West: <i>“Money ain’t real, time ain’t real”</i>. The relationship between Corporate Surrealism and time is complex and important, but we can save it for later — what is more immediately interesting is that this sort of symbolic liquidity and transmutation of vibes in the cryptocurrency world is manifestly displaying the non-reality of money. Capitalism is again being pushed to its point of autocritique, in the sense of Nick Land’s interpretation of Kant. In a way, NFT profile pictures even point to a territory beyond capitalism and into something resembling archaic economy, given that the fungibility of money in a specific currency is intrinsic to the structure of capitalism.</p>

		<p>Kanye is a positive example of Corporate Surrealism because he steers his corporate entities in a faith-based and expression-based manner that has little to do with Realist understanding about how money is made. “You know white people; get money, don’t spend it”. Instead of following the capitalist logic of accumulating money gradually and methodically year after year, quarter after quarter, Kanye follows a Prosperity Gospel based mindset in which he regularly loses all of his money because he expects that God will give it back to him manyfold if he serves him well (and this does appear to be successful for him). This is one example of a surreal attitude towards money, but it is not the only possible one.</p>

		<p>There will be more writing soon, but the real active steps towards developing Corporate Surrealism are to establish and scale surreal corporations. We are attempting to build Harmless AI on Corporate Surrealist principles, and I am also contributing to WagonDAO, a surreal corporation based out of a property in Wyoming and centered around anti-state politics and Christian spirituality. I want to also develop a surreal corporation for the arts and culture and fashion headquartered in New York City. It could perhaps just be called “The Surreal Corporation NYC” or something and become the paradigmatic one. But I’m not really sure how we would get this off the ground yet; it’s probably a ways away from actually manifesting right now.</p>
    </div>
  )
}

export const Head: HeadFC = () => <title>The Corporate Surrealist Vibe Shift</title>

export default CSVSPage

