import * as React from "react"
import type { HeadFC, PageProps } from "gatsby"
import "./index.scss"

const GuattariGangPage: React.FC<PageProps> = () => {
  return (
    <div className="container">
    <h1>Guattari Gang</h1>
		<p>Recently I have made major strides in my perhaps-pathological quest to obsessively reread Deleuze & Guattari’s texts until I feel as if I have mastered them by stumbling upon a key insight: Guattari is more important than Deleuze.</p>

<p>People will admit that <i>Anti-Oedipus</i> is almost entirely Guattari’s text and that Deleuze primarily served as editor. But when one reads Guattari’s solo works written between the publication of <i>Anti-Oedipus</i> and <i>A Thousand Plateaus</i> (eg <i>The Machinic Unconscious</i>), it seems clear that the majority of ideas in the second volume must be Guattari’s as well — or at least he is the one supplying the primary ideational thrust which then gets reinforced and filled in by the extraordinary Deleuze.</p>

<p>Yet somehow, people get it all backwards. People will hold up a copy of <i>A Thousand Plateaus</i> and tell you they’re “reading Deleuze”, not even bothering to mention the other man’s name on the cover. Guattari is usually referred to by academics in secondary texts as being an inferior thinker to Deleuze, or half-dismissed as being highly misguided or limited in certain ways, etc.</p> 

<p>In Deleuze & Guattari’s work, there is a consistent theme in which they seem to be aiming to write a text that would be impossible to read without the reader being propelled in the direction of radical progressive change, and while they acknowledge their work will be captured and stripped of its radical content by institutions, bureaucracy, they are doing everything to make this capture difficult. Dismissing Guattari is one such avenue by which the status quo may neuter the power of these texts. All of the active, vital material in D&G comes from Guattari; all of the vectors towards radical social and personal change.</p>

<p>Let’s say that Guattari’s program for sociopolitical change (though he frequently rotates names, insists that all his programs are overlapping & inseparable, etc) is called <i>molecular revolution</i>, and his program for personal-psychic change is called <i>schizoanalysis</i>. The mission of Guattari Gang would be to revive these programs and make them usable for a new generation, by excavating the texts and discovering a way to make Guattari’s concepts more workable and active.</p>

<p>I’ve decided that I’m really sick of “philosophy”. “Philosophy” seems to be a discourse that is primarily characterized by a lot of argument rather than collaborative truth-seeking, and secondly characterized by this dynamic where everyone is carrying around a bunch of dead European men in their back pocket to use like Yu-Gi-Oh trap cards in this aforementioned debate. “Aha, you have given Hume’s response to Hegel, but then what would Freud in turn respond to Hume?” This sort of thing. The absolute worst discourse of “philosophy” at its most cancerous is when people are trying to win debates merely based on the criteria that they have read a philosophy book the other person hasn’t read, like Logo Daedalus. It’s like we can’t talk about anything without assigning each other a bunch of homework. Let’s all learn how to think and speak for ourselves for once, okay!?</p>

<p>What is cool about Guattari is that he is not a philosopher. He starts out as a psychoanalyst, but then after the elaborate deconstruction of Lacanian psychoanalysis in Anti-Oedipus, he is no longer even that. He starts building a new discipline that has little to do with finding a position in relation to something said by some other European man, but rather combines insights from anthropology, biology, ecology, physics, literature, mathematics, music, etc., into a sort of loose system for comprehending the totality.</p> 

<p>By contrast, Deleuze is a philosopher, or in his words, a “pure metaphysician”, who is very much playing this game of relating a bunch of dead European men to each other. Which is fine, someone has to, but this feels like a secondary means through which the power of the D&G texts are stripped of their raw power and integrated into an institutional context. Instead of discussing what it would look like if we applied schizoanalysis to our problems today, we just endlessly talk about how we can interpret this chapter of D&G by reference to Spinoza, this next one is a novel commentary on Bergson, this one is fundamentally Platonist, etc. There’s this unfortunate dynamic with the D&G texts in which it feels like the typical reader “comes for Guattari, but stays for Deleuze”. The texts are initially exciting and interesting because they present this viciously radical vision for how to live one’s life, revolution, wild ideas like the creative power of schizophrenia, etc., but then the more one becomes moored in the standard discourse surrounding the texts, the more suddenly one realizes with horror that all you’ve been led to do is spend years arguing about reinterpretations of Kant. How did that happen?</p>

<p>There’s at least one obvious problem to applying Guattari’s ideas widely: the texts are fucking impossible to understand, full of bizarre and inexplicable statements like “God is a lobster” and “the body without organs is an egg”. As one of my friends said, “it’s like <i>Finnegans Wake”</i>. I think the fundamental problem with D&G is that Guattari doesn’t know how to write on his own, so he seeks out Deleuze for help. But Deleuze is an obscurantist writer — who prefers to make his ideas difficult to receive so that the reader is forced to think through them for himself and thus he only receives them if he is worthy — so this doesn’t help much either. D&G seem to have self-gatekept themselves well to avoid the ideas being profoundly profaned and bastardized, but at the potential downside of having the ideas underused. It might be time for a new form of presentation to push the concepts towards the other end of this tradeoff, especially in an era of waning institutional credibility in which some have foretold the rise of widespread collective internet scholarship and counter-universities as the coming norm for serious thinkers.</p>

<p>I’ll expand on this by articulating why I feel that Guattari’s ideas of molecular revolution and schizoanalysis are important and should be revived in the current age</p>

<h3>1. Molecular revolution</h3>

<p>To me, the fundamental question for thought is: how do we improve the human condition? For a long time, the philosophical hope for humanity was thought to reside in Marx, or at least in the concept of socialist revolution. But we all know what ended up happening: the revolution went bad, leading to the legacy of Marxist-Leninist states, which have a mixed record at best, to say the least.</p>

<p>To Guattari, part of the reason that the Marxist-Leninist projects failed to improve human life is that their states effected an insufficiently thorough transformation of society, putting new flags and banners on top of something that is effectively state capitalism. The true revolution needs to be “molecular” in the sense that: if you conceive of human economic actors as analogous to molecules in a solution, a revolution is only meaningful if afterwards, every molecule is doing something different; moving around entirely differently. We all are currently “doing capitalism” — and in more subtle ways than just showing up to work and making money — and so in order to have the type of change we want, we need to figure out how to apply a thorough change to society after which every person will be doing something entirely different.</p>

<p>In the current year 2023, capitalism feels increasingly unstable, incoherent and impossible to live under, yet it is not possible for any serious person to imagine that 20th century socialist dreams like global communism, proletarian revolution are possible either. Nor is there any newer progressive model for transforming society being presented as an alternative. This leads to the near-certainty of far-right reactionary “solutions” slipping in to fill the role of models for what a better society could look like.</p>

<p>The concept of molecular revolution takes advantage of an idea from molecular physics to give us hope. Prigogine and Stengers have demonstrated that when a thermodynamic system is in “far-from-equilibrium” conditions of high intensity, a sudden change in the system can occur in which the entire system spontaneously changes at once to reflect a new order emerging suddenly out of a chaotic mixture. This breaks the standard model of causality: Prigogine and Stengers say that the new system which arises after the critical point is reached is not predictable from observing the state of the system before. The basic example is a “chemical clock”, a solution in which a chaotic gray mixture can suffer a change in which a sudden reaction occurs to turn the whole mixture white at once, then black after a few seconds, then white again, then black, etc., which can be observed in a beaker. (Might be butchering some of this science because it’s from memory, don’t quote me).</p>

<p>Guattari’s shift in political perspective stems from the May 1968 events, in which there were sudden insurrections and for a moment it seemed as if there could be a communist revolution in France. The organized communist parties took a conservative attitude, protesting that the timing of the revolution made no sense given Marxist laws of history and the supposed objective conditions, but the workers and students pushed for the revolution to continue, which led Guattari to decide that formal party structure was a hindrance to the project of revolution.</p>

<p>Guattari abandons the Marxist notion that history has a rational, developmental structure which can be determined by scientific laws. History is sudden, chaotic, and unpredictable. May 1968 reflects a situation where enough stresses to the system piled up upon one another that for a moment it seemed as if they had reached a “tipping point”, and a chain reaction suddenly threatened to turn all of society on its head. However, the reaction ran out of energy far too early, and the system cooled down to something resembling its previous equilibrium state. Guattari thinks that both the beginning and the end of the May 1968 proto-revolution happened because of chaotic factors and not rules of history which can be made rational in retrospect. The next shock to the system might happen whenever, and it might go differently.</p> 

<p>Thus, the goal for the theorist of molecular revolution is not to imagine that she can predict history, find a set of rational laws determining it, or discover the plan for a better society in advance which then might be applied later. Rather, what we can do is lay a sort of theoretical and practical groundwork for seizing upon moments in which a process of radical change suddenly kicks off without anyone necessarily expecting it — we must figure out how to cultivate the fertile grounds for these moments, and prolong and amplify them once they do occur.</p> 

<p>The attitude of molecular revolution is somewhat similar to Heidegger’s idea that “only a God can save us” from contemporary technological society. Specifically, it is like the idea that the philosopher cannot present a plan to save society, but merely lay the grounds for a “God” to arrive (which in this context would mean a future sudden rapid series of unpredictable psychosocial shifts). But unlike Heidegger, who retreats to quietism and poetics, Guattari presents a number of formula and schemes for doing positive work in the meantime.</p>

<h3>2. Schizoanalysis</h3> 

<p>Schizoanalysis is a model for therapeutics that deviates from psychoanalysis in a few simple ways, mainly</p>

<p>i. You don’t see an analyst; it can be done alone, or in groups, or out on walks, in art, or wherever. More fundamentally though, no one is around claiming to “interpret” or “discover” anything in the unconscious, ie no “there is a dog in your dream, this probably represents your father”. Instead, we are only interested in modeling how the system works. This makes schizoanalysis a lot simpler than psychoanalysis in a way: we can get rid of all the complex frameworks for interpretation. We still believe in repression, but it’s more like — oh look, there is a repression here, maybe one day you might decide to do something about it.</p>

<p>ii. We don’t think it’s possible to understand an individual’s psyche aside from all the social relationships he finds himself in: not just his immediate family but also life at his work and school, all the way up to macro structures like capitalism and the nation-state. In fact, we don’t believe in an “individual psyche” — there is only the collective unconscious, since our unconscious desires are constantly being formed and planted by other people.</p>

<p>iii. Schizoanalysis is opinionated. In all systems — individuals, groups, societies — we can identify a tendency for them to develop in a progressive direction, and a counter-tendency for them to develop in a reactionary direction. We want to push them in the progressive trajectory. It should go without saying that this binary (which D&G give a number of new names for) does not imply a direct mapping onto the US political divide, the liberal notion of progress, or the Marxist notion. It does not mean either that everything is synced to a single plan of linear development, as in the liberal or Marxist ideals, or is evolving in the same direction, or on the same time-scale. It merely means that we can identity a positive direction of creativity, novelty, and growth, as well as the opposite.</p>

<p>For me personally, I’ve pretty definitively abandoned any hope in therapists being worth it, doing anything to help me fundamentally overcome my mental health issues, or being much more than scam artists who provide a vague feeling of comfort at an exorbitant price.</p> 

<p>There’s an “owl of Minerva flies at dusk” aspect to D&G’s critiques of psychoanalysis — they made them in the last years when people still believed psychoanalysis could be widely applicable as a solution to individual and societal problems. Psychoanalysis is essentially archaic at this point, and its biggest fans tend to have an antiquarian quality to them, like fans of jazz, absinthe, or bourgeois novels. Furthermore, the “radical” fans of psychoanalysis out there today tend to be primarily interested in it as a form of introspection and/or media critique, which is definitively not what its originators intended it for: they meant for it to be used for analysts, to treat patients, in a one-on-one setting, quite explicitly. So really: we should all be doing schizoanalysis instead! Or everyone is grasping at something like schizoanalysis, kind of badly.</p>

<p>I’m really interested in the emerging scene around therapeutic practices like Internal Family Systems or books like <i>The Body Keeps the Score</i>. Hearing about people doing this was the highlight of Vibe Camp for me. These new frameworks can be done with a therapist, but people use the workbooks to do these new forms of introspection in which one breaks down the self into “parts”, then re-integrates the self. Then there are these loose communities in which people share what they have learned and integrated with each other. Friends have reported the exercises in books like this, particularly <i>Existential Kink</i> which is apparently terribly written and looks like a trashy erotic novel if one were to judge by the cover, to be shockingly, dramatically effective, whereas most people I know in therapy seem to spend years stagnant, talking about it in these sorts of pious tones: “you know, I think it’s doing a lot of good for me, I think I really need it”.</p> 

<p>I still have to actually read these books, but maybe one idea for Guattari Gang would be to revive schizoanalytic theory in a way that establishes bridges with these new paradigms as actual practices and communities. There’s a certain problem to me in these holistic new-age therapeutic paradigms in that they often seek to direct the unconscious with statements that are meant to be taken on authority. Even just stuff like: “you matter, you are loved, you are valid” — it sounds nice, but can you actually prove that to me? At worst, this ties into stuff like astrology and tarot readings, where you just make the decision to believe a bunch of arbitrary bullshit, because, I guess, at least it has nothing to do with dominant scientific ontology, which means it provides a counter-narrative to hack your way out of things?</p>

<p>New-age therapeutics are often described as “woo”, because the idea is, you have to wave your hands and go woo-woo when you make certain statements — they can’t be grounded in reason, so they must be presented with mystery and aura. Historicizing them more, bringing them into relation with Western philosophy and political structures could help. Or: a lot of people in these circles will then integrate these paradigms with Western Buddhist styles of meditation, which I tend to dislike for various reasons. Schizoanalysis could be an alternative means of integrating these practices with experiences of the sublime or references to a philosophical absolute.</p>

<p>—</p> 

<p>So, the goals of Guattari Gang having been established, what are the first steps? I am still working through my reading project of re-reading the major texts, along with Guattari’s lesser-known solo work. One goal I have is to eventually do a series of YouTube lectures on <i>Capitalism & Schizophrenia</i>, through which I feel like I could perhaps make the text more accessible than it has ever been made before. This probably couldn’t be done until next year at the earliest though, since I still think I need to deepen my mastery of the text before I can make an authoritative commentary on it. I am planning to co-lead an <i>Anti-Oedipus</i> reading group this summer in NYC though.</p>

<p>The other goal I have is to build the Guattari Glossary, in which all of Guattari’s concepts in his ontology could be built into a reference source with clear examples of how they can be applied and from where they derived. One of my hot takes is that D&G basically failed to build a nonlinear “rhizome” according to their own criteria in the writing of <i>A Thousand Plateaus</i>: ime you can only really get much out of the text when you read it carefully, in order. But with the internet, it’s much easier to create real rhizomes (everything described as a “rabbit hole” is probably a rhizome, since the rhizome is initially described as “an animal burrow”, the terms are functionally equivalent). Feel pretty comfortable saying that my own writing project is evolving quite rhizomatically across this site, Realityspammer substack, and Harmless AI, especially if the defining characteristic of a rhizome is “having multiple entrances”.</p>

<p>There’s no knowing ahead of time the expanse across which a Guattari Gang rhizome could possibly stretch, how dense a web of hyperlinks we could create if the concepts begin to spread and take on a life of their own. In the best possible case, the concepts would deterritorialize to the point where they take on different names, people use them without being aware of their source, people stop feeling the necessity to read long ass difficult books like <i>Capitalism & Schizophrenia</i>, and no one really has the need to mention Guattari’s name or anyone else’s name again.</p> 
    </div>
  )
}

export const Head: HeadFC = () => <title>Guattari Gang</title>

export default GuattariGangPage

