import * as React from "react"
import type { HeadFC, PageProps } from "gatsby"
import "./index.scss"

const NationalSocialism: React.FC<PageProps> = () => {
  return (
    <div className="container">
    <h1>On National Socialism</h1>
		<div><a href="/">← Home</a></div>
		<p>
		<i>“Oh no, it says ‘On National Socialism’, is he about to say something impossibly controversial and brave?”</i> You will have to read on to find out.
		</p>
		<p>
The paradox I want to begin this note by investigating is: why is it the case that we use the word “fascism” all the time to describe the negative outcome for civilization — we take moral offense to something so we call it “fascist”, we talk about the danger of America falling into “fascism”, “fascism” becomes the term that is used for cruelty and injustice in general — when the situation we have in mind that we are scared of is not Mussolini’s Italy, but rather Adolf Hitler’s Germany, which called itself National Socialist?
</p>
		<p>
Hitler and his men did not think of themselves as “fascists” or call themselves this. While they saw Mussolini’s regime as being another example of the phenomena that their politics represented, emerging from the same spiritual soil, they saw Mussolini as the less competent and important predecessor to themselves, and did not call themselves by his name.
</p>
		<p>
Every so often, someone will cause a bit of a stir — <a href="https://twitter.com/jmrphy/status/1646345111314264066">most recently for example Justin Murphy</a> — for telling the world that they looked into Mussolini’s regime and, you guys, Mussolini is not really that bad. The purpose of this note is naturally not to praise Mussolini, but it is pretty difficult to escape the objective historical judgment that, held against Hitler, Mussolini looks very normal. This is not to say that Mussolini’s record is free from horrific mass slaughters — the singular example that comes to mind is the Yekatit 12 massacre in Ethiopia, in which Italian military leadership decided that in response to an assassination attempt, Italian soldiers would be allowed for three days to run around and rape and murder however many Ethiopians they wanted to without any mercy, a massacre during which roughly a fifth of the population of Addis Ababa were killed. But still, this is not an incredible outlier from the records of other European colonial powers. Meanwhile, at home, Italian fascism was often described as a “phony dictatorship” in which society basically operated as it did before Mussolini, unless you were a notable leftist or went out of your way to anger the regime. And Mussolini himself had little interest in racial supremacy or anti-Semitism until Hitler’s diplomacy pressured him into adopting parallel ideologies to the Germans.
</p>
		<p>
By contrast, Hitler’s regime seems to represent nothing but a total psychosocial apocalypse manifest on a scale of a hundred million people. All of society is transformed through bleak obedience into a machine made solely to win an endless, impossible war in which plans to exterminate hundreds of millions of innocent people, women and children, are calmly drafted and executed despite all lack of practical gain of the system in doing so. (Hitler might have a shot at conquering the East if he had prevented himself as a liberator from Stalinism and ruled with a gentler fist, but if you decide you are going to depopulate a region by killing every last person, you force the enemy to fight to the bloody death, every last man). There is this sense of National Socialist Germany that they were not even particularly trying to win the war, rather playing out the type of logic we now see in the mass shooter on an enormous scale — fighting to defend some tortured romantic  sense of wounded honor, not even to win, a course which requires revenge on the world on an unthinkably cruel scale. We have in National Socialism a nightmarish regression that is equal parts barbaric and psychotic in what was once seen as the home of the forefront of Western culture and civilization. 
</p>
		<p>
Of the various regimes described as fascist, there is little agreement in either the state ideology or the actual form of the state structure. Germany under Hitler, Italy under Mussolini, Spain under Franco, Romania under Antonescu, maybe some others depending on your definition, all look quite different. Franco is even more “normal” in practice than Mussolini. Given all this, and the murky historical origins of the term, it is not clear what the definition of fascism is, or if the term has much meaning at all. But we use the term, because we want to gesture at the utter catastrophe that is Hitler. 
</p>
		<p>
So why not just say National Socialism?
</p>
		<p>
My thesis is that we can’t do this, because we actually like National Socialism — that is to say, wealth sharing within a nation state under the umbrella of a shared national identity. 
</p>
		<p>
Or maybe even the case can be put more strongly: nearly all of us are National Socialists, and no political position other than National Socialism is actually possible, in a certain sense. So we can’t use National Socialism as synonymous with evil — we don’t want to apply that label to something we like.
</p>
		<p>
(An interrelated phenomenon — the ridiculous and embarrassing use of English-language academics calling Hitler’s ideology “Nazism” even in a formal context. “Nazism” was a slang term invented to mock the NSDAP, the fact that people use it today is like if the term that stuck to describe right-wing economic populism was “Drumpfism”. Again, we don’t want to say “National Socialism”.)
</p>
		<p>
Why? Because Bernie Sanders is a National Socialist. The Scandinavian social democracies, often represented as the peak of attainable paradise on earth, are National Socialist. The actually-existing-socialist countries, eg Cuba, Vietnam, are National Socialist. There is basically no hopeful scheme to improve the human condition with any degree of realism that is not wealth-sharing within the form of a nation state under an umbrella of national identity.
</p>
		<p>
At this point, it sounds like we could be making an argument in favor of National Socialism. If National Socialism is just a “normal” system of governance, and everyone is in fact doing it all the time and asking for more of it, then why do we have the taboo against saying: let’s all be National Socialists? The barrier is the argument ad Hitlerum — it seems as if we do not yet understand the mass psychological catastrophe of Hitler’s Germany, we ward it off like the devil, we do not want to invite it in by saying its name. The question of whether or not the taboo against National Socialism should be maintained is really whether or not Hitler is a chained demon that will eventually re-emerge, or if he has been banished to the shadow realm forever by the bombing of Berlin.
</p>
		<p>
According to <i>Globalists</i> by Quinn Slobodian, a book I would definitely recommend (and a serious academic text despite the InfoWars-y name), society has come to be ruled by a doctrine of political economy called neoliberalism — a term that should probably be familiar to the reader. Neoliberalism is an economic paradigm that is devised by intellectuals starting in the 1920s, and then gradually grows in its covert influence to rule over all of society in fits and starts, first by establishing the “international order” after the Second World War, and secondarily after the economic crises of the 70s, after which privatization, marketization, and financialization are applied at home in Western countries to eliminate the lingering pseudo-socialist aspects of their economies.
</p>
		<p>
According to Slobodian’s narrative, the primary opponent of neoliberalism is the fear of “economic nationalism”. After the First World War, Europe was divided into polities based on the principle of nation-states for ethnic self-determination, which would then enter a League of Nations to resolve their disputes — a scheme many commenters at the time could tell was rickety and fated for disaster. In particular, the neoliberals noticed that politicians now had an incentive to grow to power by promising as much wealth as possible for their people — bread, circuses, wealth, and a pony for everyone — and then run up a debt which could only be paid via pillaging a neighboring nation, something the masses would be all too eager to do given the racial constructions of the nations and the perennial appeal of chauvinism, especially under the right rabble-rousing figurehead who can use war to consolidate their power and legacy. What had emerged was not a stable equilibrium, far from it. The only possible outcome once this structure is set up is endless war, the neoliberals argued, and of course this bloody prophecy is what actually happened.
</p>
		<p>
After the victory in Second World War, unlike with the First, very few borders were redrawn on the map. The structure of the ethnically-constructed nation-states that had been so disastrous remained nevertheless unaltered in form. However, a much more robust globalist order was constructed via organizations like the United Nations, the World Bank, the International Monetary Fund — this would be a specifically functional economic new world order, not just a political league. This was all due to the designs of the neoliberals, who, naturally, blamed the war on economic nationalism. In their view, it was now clear that the idea that a population of a nation-state could vote on how the state’s economy is managed had to be abandoned. The neoliberals, who emerged from Austria, had great nostalgia for the Austro-Hungarian Empire, under which many ethnic groups peacefully coexisted governed under a non-democratic liberal framework with no self-rule, but nevertheless enjoyed increased prosperity through mutual trade and the ability to gather together in the flourishing cosmopolitan hubs of Vienna, Prague, and Budapest. This non-democratic management of a multi-ethnic empire by the Hapsburgs is what the neoliberals saw as successful and hoped to formalize and revive in their systems for global leadership.
</p>
		<p>
The neoliberals envisioned a world in which there would be no possibility of economic nationalism, ie National Socialism, because populations of nation-states would not be given the opportunity to vote on their political economy. Democracy would be preserved, but the masses would be exclusively allowed to vote on “culture” — whatever that means, an especially meaningless idea in the era of mass privatized corporate media. So neoliberalism is in its origins a covert doctrine based on a lie: we tell you you live in a democracy, but we know you don’t, we’re not going to actually let you do that, sorry.
</p>
		<p>
This deceit is going to be the reason that the crisis of neoliberalism will only intensify. Neoliberalism itself is a sort of double bind. On the one hand, it is grounded on the idea that you want National Socialism, but you can’t have it, sorry. On the other, it is consoling you, teasing you with the promise that you one day might get it. Every American has been told since birth that they deserve National Socialism, and when, every election cycle, a politician comes claiming to restore the American Dream, he is telling the American masses he will finally give them what they deserve. Even the basic uncontroversial idea of making appeals to the middle class is a concept which falls along these lines.
</p>
		<p>
The Norman Rockwell America of the 1950s is by nearly everyone seen as the baseline expectation of what our country should offer us. Even when left-liberals argue against it, it is in a certain histrionic way, not expecting its logic to seriously shatter, or simply critiquing it in order to subsume brown and queer people better into it and thus have it strengthened. This was America as its most National Socialist — partially through the democratic process, after the passing of the New Deal, but then secondarily through a cartel of globalist elites in business, military, and government, who pitched designed and marketed the American Dream — the economic promise in which if you were an able-bodied man and worked hard you could enter the middle class, have a house and car, and feed a family of four. This was done in order to provide a National Socialist alternative to the dreams sold by the ideological rival of Marxism-Leninism, as well as maintain a large reserve military labor force of healthy patriotic men willing to defend the homeland in the event of the apocalyptic third world war everyone was predicting. 
</p>
		<p>
This American Dream is an artificial socialist intervention on top of the capital markets — operating on their own, there is no reason the labor markets will give the average semi-skilled laborer economic stability and dignity. This is not a comfort which the neoliberals are particularly interested in maintaining. But the masses were never told that this promise had been cancelled either — at least not in such terms. A semi-skilled white man whose family had been born middle class might be downwardly mobile now, his friends are on fentanyl, etc. He is angry, he is saying “Why do I have to compete with all these immigrants now? Don’t I deserve more?” According to neoliberalism, of course he doesn’t. There is absolutely no reason why he deserves to have an easier time in the labor market on account of his race or being some kind of “traditional” American compared to an immigrant. Capitalism intrinsically relies on a slave-like underclass working grueling hours so that the upper classes get to enjoy comfort, and there is absolutely no meaningful reason why elites in America should care if a poor person in America or a poor person in Guatemala is the one breaking their back for their latte. Like Paris Hilton’s shirt says: just stop being poor. But, according to the logic of National Socialism — which was marketed, sold, and remains active in fantasy and implicit in rhetoric, but was never explicitly articulated either — he actually is entitled to the American Dream, and his rulers are denying him his birthright. His best shot is to urge those who hold National Socialism implicitly as an ideal to articulate it actively in rhetoric then aim to place it in power.
</p>
		<p>
Neoliberalism, on the other hand, can never state its stance openly. Margaret Thatcher at one point did when she said “there is no such thing as society”, but this message didn’t stick (“we live in a society” being a common refrain of critique… in a way we actually don’t). If you live in America, you are better off learning as quickly as possible that no one is going to care for you or save you other than your immediate family (if you’re lucky to have good ones) and focus on securing your bag, getting clout, total war of all against all for these resources, and we’re not all going to be winners, get rich or die trying, there is no other reward or possibility within the logic of the system. Neoliberals can at least claim that this system “works”, in the sense that it is in power, it is impossible to shake loose or even erode, and it seems to be able to ensure trade and thus lead to greater global wealth and the lessening of great power conflict over time. But at the same time it is not defensible when spoken out loud, so it is only alluded to. They certainly try to communicate it — this capitalist ideology of pull yourself up by your bootstraps, grindset, etc. — but this never really sticks. Why can’t we just say that no one in this country actually really gives a fuck about anyone else or needs to? Perhaps something is there in man that always needs to be reassured he is cared for by some kind of community, or perhaps it is just that if people really internalized this that it is them against the world, fuck everyone else, the baseline social trust required to sustain a functioning market would not be possible anymore — people would no longer be orderly when standing in line in queues, merchants would regularly defraud credit card companies, etc.
</p>
		<p>
In the years since Trump’s election, a sort of loose mass political “realignment” has been posited on the behalf of a variety of writers, many of whom are of the general sphere associated with Russian funding, or in dialogue with figures like Dugin. This new notion that is being posited of “multipolarity” or an “internationalist” world order overcoming a neoliberal globalist one is one in which all nations become self-consciously National Socialist and work out their differences through, one supposes, politics, rather than neoliberal regulating bodies. Insurging “right-wing populist” leaders such as Trump, Putin, Erdogan, Modi, Bolsanaro, and moments such as Brexit are seen as heralding this as the fundamental threat to neoliberalism. Strangely, there is also a “nationalist international” of alliances between loyalists to these different rising populist leaders across borders. This international front can be seen as instrumental in Trump’s 2016 victory. But there is no similarly networked movement across any kind of populist left.
</p>
		<p>
But while this multipolar ideology presents itself as ushering in a new sort of global peace, one in which the US does not have to wage endless global war as a unipolar hegemon — it fails to dialogue with the reason neoliberal globalism actually came into being in the first place. The plight of Bryce, the Michigan welder working for worse and worse wages seeing no hope for his future, is perhaps unfortunate, but it is of no matter for the neoliberal globalist, who is an elitist whose political mind is occupied with matters of far more import than his suffering neighbor (Bryce still has it better off than nearly everyone in the third world anyway). The problem is how to avoid planetary apocalypse. If the Third World War happens — if the next Hitler has nuclear weapons — there is no guarantee that anything whatsoever of value will survive. And the dream of a “multipolar” world of nation-states is simply an uncreative return to that which existed under the League of Nations, which was an utter disaster which lasted only twenty years before leading to an unrepeatable cataclysm. These are the stakes here. Sorry Bryce, but I hope one day you might understand — if God and the afterlife is real, you might get your reward for your suffering there, after a lifetime of drinking and angrily blogging about statues on Epstein’s island. Also, I happen to notice that after Putin’s invasion of Ukraine and the resulting mass civilian casualties, you stopped hearing this line of argument as much.
</p>
		<p>
Neoliberalism has noticed that, given the existing formal structures we exist within — capitalism, the nation-state, the nuclear family, bureaucracy — if you send the masses to the ballot box and ask them what they want out of all this, <b>they will choose National Socialism every time</b>. They will vote away their own freedoms underneath a tyranny of the majority, because to be told you are inherently worth it and will be given everything is infinitely more gratifying than the opportunity to exert any sort of political right (as long as you are in the majority). The only vehicle neoliberalism has to deny this is to postulate the meaningless binary between “democracy” (good) and “populism” (bad), a distinction which is never given any definition or coherence.
</p>
		<p>
National Socialism has nothing in common with socialism as such — here not meaning of course the socialism of the Marxist-Leninist countries, which is also National Socialism — but the ideal of socialism, the specter haunting man, a situation which has never yet existed except under primitive economies and in certain religious communal experiments. Socialism as such is the idea that social life and economic life can become one, or at least trend closer together, rather than exist torn apart as they are today leading to conditions of such exploitation, inauthenticity and alienation. Socialism is like the culture where you share a cigarette outside the nightclub with the man who happens to be asking for it. By contrast, National Socialism is the idea that after you participate in capitalism, when you pay taxes, a bureaucracy might reinvest it in social programs which benefit you, on the account of you “belonging” in the nation, a strange and indefinite abstraction.
</p>
		<p>
We have seen that both neoliberalism and National Socialism contain rhetorical contradictions which prevent their positions from being expressed in full out loud. Everything we have said so far here is the utterly unspeakable reality of what passes for today’s political “spectrum” and the range of possible decisions.
</p>
		<p>
We can also address the core contradictions in both models, those which go deeper than rhetoric. National Socialism can only ever fail and break down, seemingly in horrifying and destructive ways, because of the incredible arbitrariness of the national borders it defines itself by. It is so hard to imagine why because this one Mexican passed a test at a border and the other one didn’t the former is my brother and my comrade and the latter may be slaughtered without pity, but this is part of the central identity that National Socialism asks me to adopt.
</p>
		<p>
I am not European, so have limited ability to speak on their issues, but from what I have been told is that everyone there feels that their political forms have reached a certain end of history in bureaucratic social democracy (a sort of National Socialism, but subsumed into the trans-national EU and under American military imperial dominance). Most political debates are finished; everyone likes the healthcare, is comfortable with the amount of taxes they must pay, etc. The only remaining question is immigration, and on this sole point a left and right divide is established.
</p>
		<p>
The problem is: under capitalism, the nation-state needs to retain and grow the number of bodies inside it, for the purposes of productivity. There are two options here. The first is to open up the borders for immigration, but as one does this, the national character becomes more pluralist and it becomes increasingly hard to justify a National Socialist identity under a sole source of origin or something like that. Thus, the average worker as immigrants wander in has reason to fear a slide into the pillowless brutal logic of neoliberalism, after too many Muslims enter and the once ineffable “nation” becomes a purely economic entity. The second option is to radically embrace biopolitics, under some slogan like “we must raise the birth rates”. (Ironically, it is the right that as of today in response to COVID has spent years waging vicious critiques of biopolitics in the public sphere, supported by the polemics of such a titan as Agamben, but also often seems willing to embrace such a policy.) Under a biopolitical regime, the individual’s autonomy against the nation (which again, is a quasi-artificial group whose identity is already falling into crisis) becomes greatly weakened, as the individual’s entire body must be given over “for” the nation: first the woman who bears multiple children for the nation, then the bodies of the children themselves. The individual is born, bred, and raised to serve the nation, but the nation has no particular goal but to maintain capitalist production and supply an economic safety net. Yet the individual’s identity is predicated on existing for that nation, and being of its majority stock, she is entitled to ask for something in return. If the nation does not offer enough to give her, she is entitled to join with the majority to wage war inside and out in order to take her riches from those who did not make these sacrifices and are not of the worthy, the sole recipients of God’s favor. This is perhaps the origin of the violent vengeful death-spiral of National Socialist Germany.
</p>
		<p>
“Progressive social democracy”, ie National Socialism with a kind, left-liberal face, is only possible because of a certain anti-democratic element preventing National Socialism’s inherent pull into its chauvinistic and self-destructive black hole. This is to say: on top of the basic fundamental forms which coordinate contemporary economic life — capitalism, the nation-state, the nuclear family, state bureaucracy — there is also an apparatus of academics, NGO-funded activists, and journalists who advocate for and promote a “humanistic” way of consideration. This is what Curtis Yarvin calls the Cathedral, and despite using Matrix-inspired metaphors to tell the reader that there are all sorts of subtle way this apparatus is controlling your mind and telling you what to think, it seems that the only specific influence that Yarvin can assign to the Cathedral is that it exerts a taboo against racism, as well as against white racial solidarity. 
</p>
		<p>
National Socialist Twitter ideologists who march under the labels of “red-brown” or “post-left” will sometimes tell you that they have abandoned “the left” because the idea that there is any actual left populism is a lie; working-class or middle-class movements all are right-aligned under dominant codes, and so, these influencers say, they choose to side with the working class. Something like this is probably true. Maybe it would be a stretch to say that American left-wing social democratic movements such as DSA or Green New Deal exist only as an extension of the Cathedral to establish the fantasy that National Socialism could be present without majoritarian racism, and enjoy no actual influence or working/middle-class support — but this seems at least directionally true. And this critique should not be confused with an elitist argument which paints the working and middle classes as morally defective due to their racism, or to argue that if we want a non-racist society they must be stewarded by their betters. Rather, under the actually existing forms, petitioning the nation state to transform into National Socialism and maintain its character through privileging a majoritarian identity is the only option they have for collective economic redress — so it is no wonder they choose it.
</p>
		<p>
All throughout this document, we have still avoided exactly describing why the Hitlerian psychosis emerged the way it did, why it does not happen under every single National Socialist experiment, and the extent to which it definitively still lurks as a monster of history. Certainly many left-wing cultural critics — Adorno, Benjamin, Marcuse, Reich, Deleuze & Guattari, Agamben — have their own articulations of how National Socialism lurks in the heart of liberal democracy, which we cannot and do not want to reprise all of here.
</p>
		<p>
But it seems like, as a speculative thesis on history, it is not inappropriate to imagine that National Socialism could potentially return to America in the maximally horrific and catastrophic manner possible. If there is any reason in the left-wing tradition of critique for why National Socialism becomes psychotic in some cases and relatively stable in others, it can be summed up in the word “crisis”. Germany experienced a mass school-shooter death spiral because its very grounds were untenable unless it acted that way, like a dog backed into a corner, squeezed by an Atlanticist geopolitical block from the West and Stalin from the East. But what is happening it right now is a much more general crisis in the capitalist forms, and America is its absolute center and point of emanation, now trembling from inability to maintain a cohesive body politic under capitalist logic within it, and external forces like Xi and Putin challenging its empire. Thus, it seems possible that Germany’s madness could even, in the long historical arc, be a mere prelude to what will happen when the same slate of problems strike the system in its very center.
</p>
		<p>
I may risk losing the reader in this paragraph because it’s a bit speculative and out of scope of this document, but it seems like to me that if America enters this phase, its violent majoritarian form will not necessarily be racial supremacy, but will be what Nick Land calls the “Human Security System” — a defense mechanism the masses adopt against technological change, especially of the “transhumanist” kind. My online friend <a href="https://twitter.com/baroquespiral">@baroquespiral</a> has written <a href="https://substack.com/@baroquespiral">an excellent piece</a> on (among other things) how this technophobic attitude is currently emerging as a center-right pseudo-consensus position he calls the “monocult”. In Hitlerite Germany’s majoritarian logic, Jews are intrinsic betrayers of the nation because of lack of commitment to the “rootedness” of the German people, their ways, their historical ties. But in the potential “monocult” “Human Security System” America, anyone who sides with changes to the logic of the body and its maintenance could be considered a betrayer of the “rootedness” of humanity itself. This scapegoating will first and foremost target queer, and specifically trans people, as betrayers of the logic of sexual reproduction. But it could expand from there to target more.
</p>
		<p>
Within the current crisis, it seems like majoritarian National Socialism is rapidly being consolidated as an option, and a slide towards it in certain discourses will continue (which is not to say that it will be victorious or culminate in its most extreme possible form). Since Trump, the crisis in American political life is being presented as a crisis in “democracy”, and “democracy” is being presented as something we must save. But neither the dominant neoliberal paradigm nor the insurgent National Socialist paradigm actually care for democracy at all, or want it. Democracy is tedious and inefficient, and its central premise conceals the flaw that most people are stupid and vulgar and probably shouldn’t be in charge of anything important, which everyone knows because everyone has to deal with them. At its best, democracy is defensible as a bulwark against arbitrary tyranny. But the Western COVID response and its overreach has introduced yet another point in the crisis by showing us in dramatic fashion that this is not necessarily the case. So “democracy” is not a strong point to lean on.
</p>
		<p>
The neoliberals, at this point, need to do what they do best: which is prolonged crisis management, deferring to technology to manage what are really social problems, and introducing dissimulating narratives and fantasies into discourse to prevent a nationalist position from attaining self-consciousness. Probably the best case scenario is for increasing disintegration of the nation-state — specifically America’s — and for more localist or communal polities to be able to absorb the demand people have for a body to offer some minor element of security or care for them. George Soros these days seems just as interested in a patchwork Snow Crash America as Curtis Yarvin was — though interestingly, Yarvin seems to have stopped advocating for this form of American Balkanization as much these days; on his new Gray Mirror blog, he sounds much more like a National Socialist.
</p>
		<p>
What other possible options can be presented?
</p>
		<p>
Absolutely none, under the existing constellation of political forms and range of intelligible discourse within them.
</p>
		<p>
If you engage or work within the political field as it is constructed, you limit yourself to these ideas. It is far better and more dignified to not touch it at all, if you are unwilling to go farther than what is presented and at hand. The only alternative possibly worth considering is one which takes these constellation of forms — capitalism, the nation-state, the nuclear family, bureaucracy — as one that is not necessarily a given, and one day might not exist.
</p>
		<p>
To make this decision is the beginning of what I am calling Surrealism, in its political sense.
</p>
		<p>
Surrealism, as the only path worth staking out towards a future, has to take several similar decisions:
</p>
		<p>
			<li>
- Continuing attention to political questions as such, while sticking to a refusal to engage with the political field as it is currently constructed, including specifically the left-right binary, which is a construct that has emerged in the aftermath of the French Revolution designating the range of possibilities for a Republican nation-state. As we have made clear in this document, this range of possibilities is not sufficient, so we do not exist on “the political spectrum”.  
</li>
<li>
- Committing to refuse to participate in the public spectacles of cruelty and despising of one’s neighbor that the system will increasingly demand as this dynamic continues, whether in the majoritarian-supremacist path or in the fragmenting neoliberal war of all against all.
</li>
<li>
- Willingness to wait for a moment of political change outside of this spectrum which might emerge suddenly, all at once, as if in a miracle. (This of course is not a physics-defying supernatural intervention, but rather a social possibility that exists entirely outside the space of what can be currently articulated or signified. That being said, physics creates a lot of potential avenues to happen via imminent technological change.)
</li>
		<p>
As we have laid these three worldviews out here — National Socialism, neoliberalism, and Surrealism — it is important to recognize that this is all very orthogonal to the left-right divide as it is typically imagined, or the ridiculous “culture war”. In all three cases, they are expressed on both side of this divide, which is increasingly becoming about arbitrary semiotics rather than actual investigation into political form. Bernie Sanders v. Naharenda Modi. Hillary Clinton v. Ben Shapiro. Ecofeminist anarchist co-ops vs. Jesus movement homesteading.
</p>
<p>
Surrealism, as the only remaining possibility, is not exactly a philosophy for mature, sober adults. It is actually a very naive and childish belief, in the sense indicated by <i>Thus Spoke Zarathustra</i>.
</p>

		<p>
I once was watching a stream by the “patriotic socialist” ideologue <a href="https://twitter.com/InfraHaz">Haz Al-Din</a>. He was characterizing his movement’s enemies as adult children, “woke snowflakes”, whose ideal of the coming society is an infantile regression in which they are projecting childish dreams and fantasizing impossible things, such as “that life will be all colorful like a video game, there will be pink jellyfish flying around in the skies” (paraphrase from memory, I wouldn’t be able to find the clip if I tried). Against this, he posits a hard headed commitment to a National Socialism based around work, industry, patriarchy, national identity, and so on.
</p>
		<p>
I think it is probably fine to accept the stakes as Haz puts it here. Yes, why not? Pink jellyfish will one day fly around in the skies. Surrealism. If you’re not willing to imagine this, I don’t see the point of doing much, there are few remaining stakes to life at all.
</p>
    </div>
  )
}

export const Head: HeadFC = () => <title>On National Socialism</title>

export default NationalSocialism

